/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ChecklistPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian9 = require("obsidian");

// src/constants.ts
var VIEW_TYPE_CHECKLIST = "checklist-view";
var VIEW_TYPE_CHECKLIST_SIDEBAR = "checklist-sidebar";
var ICON_CHECKLIST = "check-square";

// src/views/ChecklistView.ts
var import_obsidian = require("obsidian");

// src/utils/filter.ts
function matchesQuery(item, query) {
  const q = query.trim().toLowerCase();
  if (!q)
    return true;
  if (item.name.toLowerCase().includes(q))
    return true;
  if (item.description.toLowerCase().includes(q))
    return true;
  for (const value of Object.values(item.properties)) {
    if (String(value).toLowerCase().includes(q))
      return true;
  }
  return false;
}
function matchesStatus(item, status) {
  if (!status || status === "all")
    return true;
  return status === "done" ? item.completed : !item.completed;
}
function matchesProperties(item, props) {
  if (!props)
    return true;
  for (const [key, expected] of Object.entries(props)) {
    const actual = item.properties[key];
    if (Array.isArray(expected)) {
      if (expected.length === 0)
        continue;
      if (!expected.some((v) => v === actual))
        return false;
    } else {
      if (actual !== expected)
        return false;
    }
  }
  return true;
}
function filterItems(items, spec) {
  return items.filter(
    (item) => {
      var _a;
      return matchesQuery(item, (_a = spec.query) != null ? _a : "") && matchesStatus(item, spec.status) && matchesProperties(item, spec.properties);
    }
  );
}

// src/utils/sort.ts
var BUILTIN_KEYS = /* @__PURE__ */ new Set(["name", "completed", "filePath", "description"]);
function getValue(item, key) {
  if (BUILTIN_KEYS.has(key)) {
    return item[key];
  }
  if (key in item.properties)
    return item.properties[key];
  return void 0;
}
function compare(a, b) {
  if (typeof a === "number" && typeof b === "number")
    return a - b;
  if (typeof a === "boolean" && typeof b === "boolean") {
    return a === b ? 0 : a ? 1 : -1;
  }
  return String(a).localeCompare(String(b), void 0, { sensitivity: "base" });
}
function sortItems(items, spec) {
  const indexed = items.map((item, index) => ({ item, index }));
  const knownKey = BUILTIN_KEYS.has(spec.key) || items.some((i) => Object.prototype.hasOwnProperty.call(i.properties, spec.key));
  if (!knownKey)
    return items.slice();
  indexed.sort((a, b) => {
    const av = getValue(a.item, spec.key);
    const bv = getValue(b.item, spec.key);
    const aMissing = av === void 0 || av === null || av === "";
    const bMissing = bv === void 0 || bv === null || bv === "";
    if (aMissing && bMissing)
      return a.index - b.index;
    if (aMissing)
      return 1;
    if (bMissing)
      return -1;
    const cmp = compare(av, bv);
    if (cmp !== 0)
      return spec.dir === "desc" ? -cmp : cmp;
    return a.index - b.index;
  });
  return indexed.map((entry) => entry.item);
}

// src/utils/applyView.ts
function applyView(items, state) {
  const filtered = state.filter ? filterItems(items, state.filter) : items.slice();
  return state.sort ? sortItems(filtered, state.sort) : filtered;
}

// src/views/ChecklistView.ts
var ChecklistView = class extends import_obsidian.ItemView {
  constructor(leaf, manager, onAddItem, onAddItems, onDeleteItem, onRefreshSidebar, onExport) {
    super(leaf);
    /** Per-checklist view state (sort + filter), kept in-memory only. */
    this.viewStateByChecklist = /* @__PURE__ */ new Map();
    this.manager = manager;
    this.onAddItem = onAddItem;
    this.onAddItems = onAddItems;
    this.onDeleteItem = onDeleteItem;
    this.onRefreshSidebar = onRefreshSidebar;
    this.onExport = onExport;
    this.contentContainer = document.createElement("div");
  }
  getViewType() {
    return VIEW_TYPE_CHECKLIST;
  }
  getDisplayText() {
    const active = this.manager.getActiveChecklist();
    return active ? active.name : "Checklist";
  }
  getIcon() {
    return ICON_CHECKLIST;
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("checklist-view-container");
    this.contentContainer = container.createDiv({ cls: "checklist-content" });
    await this.renderView();
  }
  async onClose() {
    this.contentContainer.empty();
  }
  async renderView() {
    this.contentContainer.empty();
    const activeChecklist = this.manager.getActiveChecklist();
    if (!activeChecklist) {
      this.renderEmptyState();
      return;
    }
    await this.renderItems(activeChecklist);
    this.renderFAB();
  }
  renderEmptyState() {
    const emptyDiv = this.contentContainer.createDiv({ cls: "checklist-empty" });
    emptyDiv.createEl("p", {
      text: "Select a checklist from the sidebar to view items.",
      cls: "checklist-empty-text"
    });
  }
  async renderItems(checklist) {
    const titleBar = this.contentContainer.createDiv({ cls: "checklist-title-bar" });
    titleBar.createEl("h4", { text: checklist.name, cls: "checklist-title" });
    const exportBtn = titleBar.createEl("button", {
      cls: "checklist-export-btn clickable-icon",
      attr: { "aria-label": "Export checklist" }
    });
    (0, import_obsidian.setIcon)(exportBtn, "download");
    exportBtn.addEventListener("click", (e) => {
      const menu = new import_obsidian.Menu();
      menu.addItem((item) => {
        item.setTitle("Export as Markdown").setIcon("file-text").onClick(() => this.onExport("markdown"));
      });
      menu.addItem((item) => {
        item.setTitle("Export as JSON").setIcon("braces").onClick(() => this.onExport("json"));
      });
      menu.showAtMouseEvent(e);
    });
    const allItems = await this.manager.getItems(checklist.id);
    const state = this.getViewState(checklist.id);
    this.renderToolbar(checklist, state);
    const items = applyView(allItems, state);
    const listContainer = this.contentContainer.createDiv({ cls: "checklist-items" });
    if (allItems.length === 0) {
      listContainer.createEl("p", {
        text: "No items yet. Add one to get started!",
        cls: "checklist-no-items"
      });
    } else {
      const headerRow = listContainer.createDiv({ cls: "checklist-header-row" });
      if (checklist.kind !== "list") {
        headerRow.createDiv({ cls: "checklist-col checklist-col-check", text: "" });
      }
      this.renderSortableHeader(
        headerRow,
        "checklist-col-name",
        "Name",
        "name",
        checklist.id,
        state
      );
      for (const prop of checklist.properties) {
        this.renderSortableHeader(
          headerRow,
          "checklist-col-prop",
          prop.name,
          prop.name,
          checklist.id,
          state
        );
      }
      headerRow.createDiv({ cls: "checklist-col checklist-col-actions", text: "" });
      if (items.length === 0) {
        listContainer.createEl("p", {
          text: "No items match the current filters.",
          cls: "checklist-no-items"
        });
      } else {
        for (const item of items) {
          this.renderItem(listContainer, item, checklist);
        }
      }
    }
    this.renderInlineAdd(listContainer, checklist);
  }
  renderItem(container, item, checklist) {
    const row = container.createDiv({ cls: "checklist-item-row" });
    if (checklist.kind !== "list") {
      const checkCell = row.createDiv({ cls: "checklist-col checklist-col-check" });
      const checkbox = checkCell.createEl("input", { type: "checkbox" });
      checkbox.checked = item.completed;
      checkbox.addEventListener("change", async () => {
        if (checkbox.checked) {
          row.addClass("checklist-item-completing");
          setTimeout(async () => {
            await this.manager.completeItem(item.filePath);
            await this.renderView();
            this.onRefreshSidebar();
          }, 300);
        }
      });
    }
    const nameCell = row.createDiv({ cls: "checklist-col checklist-col-name" });
    nameCell.createSpan({ text: item.name, cls: "checklist-item-name" });
    if (item.description) {
      nameCell.createEl("small", {
        text: item.description,
        cls: "checklist-item-desc"
      });
    }
    for (const prop of checklist.properties) {
      const value = item.properties[prop.name] || "";
      row.createDiv({
        cls: "checklist-col checklist-col-prop",
        text: String(value)
      });
    }
    const actionsCell = row.createDiv({ cls: "checklist-col checklist-col-actions" });
    const deleteBtn = actionsCell.createEl("button", {
      cls: "checklist-item-delete clickable-icon",
      attr: { "aria-label": "Delete item" }
    });
    (0, import_obsidian.setIcon)(deleteBtn, "trash-2");
    deleteBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.onDeleteItem(item.filePath);
    });
    row.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      const menu = new import_obsidian.Menu();
      menu.addItem((menuItem) => {
        menuItem.setTitle("Delete item").setIcon("trash-2").onClick(() => this.onDeleteItem(item.filePath));
      });
      menu.showAtMouseEvent(e);
    });
  }
  getViewState(checklistId) {
    let state = this.viewStateByChecklist.get(checklistId);
    if (!state) {
      state = { filter: { query: "", status: "all" } };
      this.viewStateByChecklist.set(checklistId, state);
    }
    return state;
  }
  renderToolbar(checklist, state) {
    var _a, _b, _c, _d;
    const toolbar = this.contentContainer.createDiv({ cls: "checklist-toolbar" });
    const search = toolbar.createEl("input", {
      type: "text",
      cls: "checklist-toolbar-search",
      attr: { placeholder: "Search items...", "aria-label": "Search items" }
    });
    search.value = (_b = (_a = state.filter) == null ? void 0 : _a.query) != null ? _b : "";
    search.addEventListener("input", async () => {
      var _a2;
      state.filter = { ...(_a2 = state.filter) != null ? _a2 : {}, query: search.value };
      await this.renderView();
      const next = this.contentContainer.querySelector(
        ".checklist-toolbar-search"
      );
      if (next) {
        next.focus();
        next.setSelectionRange(next.value.length, next.value.length);
      }
    });
    const statusSelect = toolbar.createEl("select", {
      cls: "checklist-toolbar-status",
      attr: { "aria-label": "Status filter" }
    });
    for (const opt of [
      { v: "all", label: "All" },
      { v: "active", label: "Active" },
      { v: "done", label: "Done" }
    ]) {
      const optEl = statusSelect.createEl("option", { text: opt.label });
      optEl.value = opt.v;
    }
    statusSelect.value = (_d = (_c = state.filter) == null ? void 0 : _c.status) != null ? _d : "all";
    statusSelect.addEventListener("change", async () => {
      var _a2;
      state.filter = {
        ...(_a2 = state.filter) != null ? _a2 : {},
        status: statusSelect.value
      };
      await this.renderView();
    });
    const clearBtn = toolbar.createEl("button", {
      cls: "checklist-toolbar-clear",
      text: "Clear",
      attr: { "aria-label": "Clear filters and sort" }
    });
    clearBtn.addEventListener("click", async () => {
      this.viewStateByChecklist.set(checklist.id, {
        filter: { query: "", status: "all" }
      });
      await this.renderView();
    });
  }
  renderSortableHeader(parent, colCls, label, key, checklistId, state) {
    var _a, _b;
    const cell = parent.createDiv({
      cls: `checklist-col ${colCls} checklist-col-sortable`
    });
    cell.createSpan({ text: label });
    const isActive = ((_a = state.sort) == null ? void 0 : _a.key) === key;
    const indicator = cell.createSpan({ cls: "checklist-sort-indicator" });
    indicator.textContent = isActive ? ((_b = state.sort) == null ? void 0 : _b.dir) === "desc" ? " \u2193" : " \u2191" : "";
    cell.addEventListener("click", async () => {
      const current = state.sort;
      let nextDir = "asc";
      if ((current == null ? void 0 : current.key) === key) {
        nextDir = current.dir === "asc" ? "desc" : "asc";
      }
      state.sort = { key, dir: nextDir };
      this.viewStateByChecklist.set(checklistId, state);
      await this.renderView();
    });
  }
  renderInlineAdd(container, checklist) {
    const inlineRow = container.createDiv({ cls: "checklist-inline-add" });
    const iconEl = inlineRow.createSpan({ cls: "checklist-inline-add-icon" });
    (0, import_obsidian.setIcon)(iconEl, "plus");
    const input = inlineRow.createEl("input", {
      type: "text",
      cls: "checklist-inline-add-input",
      attr: { placeholder: "Add new item..." }
    });
    input.addEventListener("keydown", async (e) => {
      if (e.key === "Enter" && input.value.trim()) {
        const name = input.value.trim();
        await this.manager.addItem(checklist.id, name, {}, "");
        input.value = "";
        await this.renderView();
        this.onRefreshSidebar();
      }
    });
  }
  renderFAB() {
    const fab = this.contentContainer.createDiv({ cls: "checklist-fab" });
    const mainBtn = fab.createEl("button", {
      cls: "checklist-fab-main",
      attr: { "aria-label": "Add items" }
    });
    (0, import_obsidian.setIcon)(mainBtn, "plus");
    const fabMenu = fab.createDiv({ cls: "checklist-fab-menu" });
    const addOneBtn = fabMenu.createEl("button", {
      cls: "checklist-fab-option",
      attr: { "aria-label": "Add single item" }
    });
    (0, import_obsidian.setIcon)(addOneBtn, "plus");
    addOneBtn.createSpan({ text: "Add Item" });
    addOneBtn.addEventListener("click", () => {
      fab.removeClass("is-open");
      this.onAddItem();
    });
    const addMultiBtn = fabMenu.createEl("button", {
      cls: "checklist-fab-option",
      attr: { "aria-label": "Add multiple items" }
    });
    (0, import_obsidian.setIcon)(addMultiBtn, "list-plus");
    addMultiBtn.createSpan({ text: "Add Multiple" });
    addMultiBtn.addEventListener("click", () => {
      fab.removeClass("is-open");
      this.onAddItems();
    });
    mainBtn.addEventListener("click", () => {
      fab.toggleClass("is-open", !fab.hasClass("is-open"));
    });
  }
};

// src/views/ChecklistSidebarView.ts
var import_obsidian2 = require("obsidian");
var ChecklistSidebarView = class extends import_obsidian2.ItemView {
  constructor(leaf, manager, onSelectChecklist, onCreateList, onDeleteChecklist, onExport) {
    super(leaf);
    this.manager = manager;
    this.onSelectChecklist = onSelectChecklist;
    this.onCreateList = onCreateList;
    this.onDeleteChecklist = onDeleteChecklist;
    this.onExport = onExport;
    this.listContainer = document.createElement("div");
  }
  getViewType() {
    return VIEW_TYPE_CHECKLIST_SIDEBAR;
  }
  getDisplayText() {
    return "Checklists";
  }
  getIcon() {
    return ICON_CHECKLIST;
  }
  async onOpen() {
    this.addAction("download", "Export all checklists", (e) => {
      const menu = new import_obsidian2.Menu();
      menu.addItem((item) => {
        item.setTitle("Export all as Markdown").setIcon("file-text").onClick(() => this.onExport(null, "markdown"));
      });
      menu.addItem((item) => {
        item.setTitle("Export all as JSON").setIcon("braces").onClick(() => this.onExport(null, "json"));
      });
      menu.showAtMouseEvent(e);
    });
    this.addAction("plus", "New checklist", () => {
      this.onCreateList();
    });
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("nav-files-container", "checklist-sidebar-container");
    const navHeader = container.createDiv({ cls: "nav-header" });
    const navButtons = navHeader.createDiv({ cls: "nav-buttons-container" });
    const newBtn = navButtons.createEl("div", {
      cls: "nav-action-button clickable-icon",
      attr: { "aria-label": "New checklist" }
    });
    (0, import_obsidian2.setIcon)(newBtn, "plus");
    newBtn.addEventListener("click", () => this.onCreateList());
    this.listContainer = container.createDiv({ cls: "nav-folder-children" });
    await this.renderView();
  }
  async onClose() {
    this.listContainer.empty();
  }
  async renderView() {
    this.listContainer.empty();
    const checklists = this.manager.getSettings().checklists;
    const activeId = this.manager.getSettings().activeChecklistId;
    if (checklists.length === 0) {
      const empty = this.listContainer.createDiv({ cls: "checklist-sidebar-empty" });
      empty.createEl("p", { text: "No checklists yet." });
      return;
    }
    for (const checklist of checklists) {
      this.renderChecklistEntry(this.listContainer, checklist, checklist.id === activeId);
    }
  }
  renderChecklistEntry(container, checklist, isActive) {
    const item = container.createDiv({ cls: "tree-item nav-file" });
    const self = item.createDiv({
      cls: `tree-item-self nav-file-title${isActive ? " is-active" : ""}`,
      attr: { "data-path": checklist.id }
    });
    const iconEl = self.createSpan({ cls: "tree-item-icon nav-file-title-icon" });
    (0, import_obsidian2.setIcon)(iconEl, ICON_CHECKLIST);
    self.createSpan({
      text: checklist.name,
      cls: "tree-item-inner nav-file-title-content"
    });
    const countEl = self.createSpan({ cls: "tree-item-flair" });
    this.manager.getItems(checklist.id).then((items) => {
      countEl.setText(String(items.length));
    });
    self.addEventListener("click", () => {
      this.onSelectChecklist(checklist.id);
    });
    self.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      const menu = new import_obsidian2.Menu();
      menu.addItem((menuItem) => {
        menuItem.setTitle("Export as Markdown").setIcon("file-text").onClick(() => this.onExport(checklist.id, "markdown"));
      });
      menu.addItem((menuItem) => {
        menuItem.setTitle("Export as JSON").setIcon("braces").onClick(() => this.onExport(checklist.id, "json"));
      });
      menu.addItem((menuItem) => {
        menuItem.setTitle("Delete checklist").setIcon("trash").onClick(() => this.onDeleteChecklist(checklist.id));
      });
      menu.showAtMouseEvent(e);
    });
  }
};

// src/services/ChecklistManager.ts
var import_obsidian3 = require("obsidian");

// src/utils/frontmatter.ts
function needsQuoting(value) {
  return value.includes(":") || value.includes("#") || value.includes("'") || value.includes('"') || value.includes("\n") || value.startsWith(" ") || value.endsWith(" ") || value === "true" || value === "false" || value === "null" || /^\d{4}-\d{2}-\d{2}/.test(value);
}
function formatYamlValue(value) {
  if (typeof value === "boolean" || typeof value === "number") {
    return String(value);
  }
  if (needsQuoting(value)) {
    return `"${value.replace(/"/g, '\\"')}"`;
  }
  return value;
}
function generateFrontmatter(properties, options = {}) {
  const includeCompleted = options.includeCompleted !== false;
  const lines = ["---"];
  for (const [key, value] of Object.entries(properties)) {
    lines.push(`${key}: ${formatYamlValue(value)}`);
  }
  if (includeCompleted && !("completed" in properties)) {
    lines.push("completed: false");
  }
  lines.push("---");
  return lines.join("\n");
}
function parseFrontmatter(content) {
  const trimmed = content.trim();
  if (!trimmed.startsWith("---")) {
    return { properties: {}, body: trimmed };
  }
  const lines = trimmed.split("\n");
  let endIndex = -1;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i].trim() === "---") {
      endIndex = i;
      break;
    }
  }
  if (endIndex === -1) {
    return { properties: {}, body: trimmed };
  }
  const properties = {};
  for (let i = 1; i < endIndex; i++) {
    const line = lines[i];
    const colonIndex = line.indexOf(":");
    if (colonIndex === -1)
      continue;
    const key = line.substring(0, colonIndex).trim();
    let value = line.substring(colonIndex + 1).trim();
    if (value.startsWith('"') && value.endsWith('"') || value.startsWith("'") && value.endsWith("'")) {
      value = value.slice(1, -1);
    }
    properties[key] = value;
  }
  const bodyLines = lines.slice(endIndex + 1);
  const body = bodyLines.join("\n").trim();
  return { properties, body };
}

// src/services/ChecklistManager.ts
function generateId() {
  return Date.now().toString(36) + Math.random().toString(36).substring(2, 8);
}
var ChecklistManager = class {
  constructor(app, settings, save) {
    this.app = app;
    this.settings = settings;
    this.save = save;
  }
  getSettings() {
    return this.settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  async syncChecklistsFromFolder(folder) {
    const baseFolder = (folder || "checklists").trim().replace(/^\/+|\/+$/g, "") || "checklists";
    const subfolderPaths = this.getImmediateSubfolderPaths(baseFolder);
    const existingByPath = new Map(
      this.settings.checklists.map((checklist) => [checklist.folderPath, checklist])
    );
    this.settings.checklists = subfolderPaths.map((folderPath) => {
      const existing = existingByPath.get(folderPath);
      if (existing)
        return existing;
      return {
        id: generateId(),
        name: folderPath.split("/").pop() || folderPath,
        folderPath,
        properties: [],
        createdAt: (/* @__PURE__ */ new Date()).toISOString(),
        kind: "checklist"
      };
    });
    if (this.settings.activeChecklistId && !this.settings.checklists.some((c) => c.id === this.settings.activeChecklistId)) {
      this.settings.activeChecklistId = null;
    }
    await this.save();
  }
  /**
   * Creates a new checklist definition and its folder.
   */
  async createChecklist(name, properties, kind = "checklist") {
    const baseFolder = (this.settings.checklistsFolder || "checklists").replace(/\/+$/, "");
    const folderPath = `${baseFolder}/${name}`;
    if (!this.app.vault.getAbstractFileByPath(baseFolder)) {
      try {
        await this.app.vault.createFolder(baseFolder);
      } catch (e) {
      }
    }
    const checklist = {
      id: generateId(),
      name,
      folderPath,
      properties,
      createdAt: (/* @__PURE__ */ new Date()).toISOString(),
      kind
    };
    this.settings.checklists.push(checklist);
    this.settings.activeChecklistId = checklist.id;
    await this.app.vault.createFolder(folderPath);
    await this.save();
    return checklist;
  }
  /**
   * Deletes a checklist definition from settings and removes all its item files.
   */
  async deleteChecklist(id) {
    const checklist = this.settings.checklists.find((c) => c.id === id);
    if (checklist) {
      const allFiles = this.app.vault.getMarkdownFiles();
      const checklistFiles = allFiles.filter(
        (f) => f.path.startsWith(checklist.folderPath + "/")
      );
      for (const file of checklistFiles) {
        await this.app.vault.delete(file);
      }
    }
    this.settings.checklists = this.settings.checklists.filter((c) => c.id !== id);
    if (this.settings.activeChecklistId === id) {
      this.settings.activeChecklistId = null;
    }
    await this.save();
  }
  /**
   * Deletes a single item (markdown file) by its file path.
   */
  async deleteItem(filePath) {
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (file instanceof import_obsidian3.TFile) {
      await this.app.vault.delete(file);
    } else {
      await this.app.vault.delete({ path: filePath });
    }
  }
  /**
   * Adds a new item (markdown file) to a checklist folder.
   */
  async addItem(checklistId, name, properties, description) {
    const [file] = await this.addItems(checklistId, [{ name, properties, description }]);
    return file;
  }
  /**
   * Adds multiple items (markdown files) to a checklist folder at once.
   */
  async addItems(checklistId, items) {
    if (items.length === 0)
      return [];
    const checklist = this.findChecklist(checklistId);
    const files = [];
    const isList = checklist.kind === "list";
    for (const item of items) {
      const mergedProperties = this.mergeProperties(checklist.properties, item.properties);
      const frontmatter = generateFrontmatter(mergedProperties, {
        includeCompleted: !isList
      });
      const content = item.description ? `${frontmatter}

${item.description}` : `${frontmatter}
`;
      const filePath = `${checklist.folderPath}/${item.name}.md`;
      const file = await this.app.vault.create(filePath, content);
      files.push(file);
    }
    return files;
  }
  /**
   * Merges provided properties with defaults from property definitions.
   */
  mergeProperties(definitions, properties) {
    const merged = {};
    for (const prop of definitions) {
      if (prop.name in properties) {
        merged[prop.name] = properties[prop.name];
      } else if (prop.defaultValue !== void 0) {
        merged[prop.name] = prop.defaultValue;
      }
    }
    for (const [key, value] of Object.entries(properties)) {
      if (!(key in merged)) {
        merged[key] = value;
      }
    }
    return merged;
  }
  /**
   * Marks an item as complete by deleting its file.
   */
  async completeItem(filePath) {
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (file instanceof import_obsidian3.TFile) {
      await this.app.vault.delete(file);
    } else {
      await this.app.vault.delete({ path: filePath });
    }
  }
  /**
   * Reads all items from a checklist's folder.
   */
  async getItems(checklistId) {
    const checklist = this.findChecklist(checklistId);
    const allFiles = this.app.vault.getMarkdownFiles();
    const checklistFiles = allFiles.filter(
      (f) => f.path.startsWith(checklist.folderPath + "/")
    );
    const items = [];
    for (const file of checklistFiles) {
      const content = await this.app.vault.read(file);
      const parsed = parseFrontmatter(content);
      items.push({
        filePath: file.path,
        name: file.basename,
        description: parsed.body,
        properties: parsed.properties,
        completed: checklist.kind === "list" ? false : parsed.properties["completed"] === "true"
      });
    }
    return items;
  }
  /**
   * Returns the active checklist definition, or null.
   */
  getActiveChecklist() {
    if (!this.settings.activeChecklistId)
      return null;
    return this.settings.checklists.find(
      (c) => c.id === this.settings.activeChecklistId
    ) || null;
  }
  /**
   * Sets the active checklist by ID.
   */
  setActiveChecklist(id) {
    this.settings.activeChecklistId = id;
    this.save();
  }
  /**
   * Exports a single checklist as a markdown string.
   */
  async exportChecklistAsMarkdown(checklistId) {
    const checklist = this.findChecklist(checklistId);
    const items = await this.getItems(checklistId);
    const lines = [`# ${checklist.name}`, ""];
    const isList = checklist.kind === "list";
    for (const item of items) {
      if (isList) {
        lines.push(`- ${item.name}`);
      } else {
        const status = item.completed ? "x" : " ";
        lines.push(`- [${status}] ${item.name}`);
      }
      for (const prop of checklist.properties) {
        const val = item.properties[prop.name];
        if (val !== void 0 && val !== "") {
          lines.push(`  - ${prop.name}: ${val}`);
        }
      }
      if (item.description) {
        lines.push(`  - ${item.description}`);
      }
    }
    return lines.join("\n") + "\n";
  }
  /**
   * Exports a single checklist as a JSON string.
   */
  async exportChecklistAsJson(checklistId) {
    const checklist = this.findChecklist(checklistId);
    const items = await this.getItems(checklistId);
    const data = {
      name: checklist.name,
      properties: checklist.properties,
      items: items.map((item) => ({
        name: item.name,
        properties: item.properties,
        description: item.description,
        completed: item.completed
      }))
    };
    return JSON.stringify(data, null, 2);
  }
  /**
   * Exports all checklists as a combined markdown string.
   */
  async exportAllAsMarkdown() {
    const checklists = this.settings.checklists;
    if (checklists.length === 0)
      return "";
    const sections = [];
    for (const checklist of checklists) {
      sections.push(await this.exportChecklistAsMarkdown(checklist.id));
    }
    return sections.join("\n");
  }
  /**
   * Exports all checklists as a JSON string.
   */
  async exportAllAsJson() {
    const checklists = this.settings.checklists;
    const allData = [];
    for (const checklist of checklists) {
      const items = await this.getItems(checklist.id);
      allData.push({
        name: checklist.name,
        properties: checklist.properties,
        items: items.map((item) => ({
          name: item.name,
          properties: item.properties,
          description: item.description,
          completed: item.completed
        }))
      });
    }
    return JSON.stringify({ checklists: allData }, null, 2);
  }
  /**
   * Finds a checklist by ID or throws.
   */
  findChecklist(id) {
    const checklist = this.settings.checklists.find((c) => c.id === id);
    if (!checklist) {
      throw new Error("Checklist not found");
    }
    return checklist;
  }
  getImmediateSubfolderPaths(baseFolder) {
    const paths = /* @__PURE__ */ new Set();
    const prefix = `${baseFolder}/`;
    const vaultWithLoadedFiles = this.app.vault;
    const loadedFiles = typeof vaultWithLoadedFiles.getAllLoadedFiles === "function" ? vaultWithLoadedFiles.getAllLoadedFiles() : this.app.vault.getMarkdownFiles();
    for (const entry of loadedFiles) {
      const path = entry.path;
      if (!path || !path.startsWith(prefix))
        continue;
      const relative = path.slice(prefix.length);
      if (!relative)
        continue;
      const segment = relative.split("/")[0];
      if (!segment)
        continue;
      if (entry instanceof import_obsidian3.TFolder || relative.includes("/")) {
        paths.add(`${baseFolder}/${segment}`);
      }
    }
    return Array.from(paths).sort((a, b) => a.localeCompare(b));
  }
};

// src/modals/CreateListModal.ts
var import_obsidian4 = require("obsidian");
var CreateListModal = class extends import_obsidian4.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.listName = "";
    this.kind = "checklist";
    this.properties = [];
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("checklist-modal");
    contentEl.createEl("h2", { text: "Create New List" });
    new import_obsidian4.Setting(contentEl).setName("Kind").setDesc("Checklist tracks completion with checkboxes; list omits checkboxes (use as a properties catalogue).").addDropdown(
      (dropdown) => dropdown.addOption("checklist", "Checklist (with checkboxes)").addOption("list", "List (no checkboxes)").setValue(this.kind).onChange((value) => {
        this.kind = value;
      })
    );
    new import_obsidian4.Setting(contentEl).setName("Name").setDesc("Name for the new list").addText(
      (text) => text.setPlaceholder("My Tasks").onChange((value) => {
        this.listName = value;
      })
    );
    contentEl.createEl("h3", { text: "Properties" });
    contentEl.createEl("p", {
      text: "Define the front matter fields for each item in this checklist.",
      cls: "setting-item-description"
    });
    const propertiesContainer = contentEl.createDiv({ cls: "checklist-properties-list" });
    this.renderProperties(propertiesContainer);
    new import_obsidian4.Setting(contentEl).addButton(
      (button) => button.setButtonText("Add Property").onClick(() => {
        this.properties.push({
          name: "",
          type: "text"
        });
        this.renderProperties(propertiesContainer);
      })
    );
    new import_obsidian4.Setting(contentEl).addButton(
      (button) => button.setButtonText("Create").setCta().onClick(() => {
        if (!this.listName.trim()) {
          new import_obsidian4.Notice("Please enter a name.");
          return;
        }
        const validProps = this.properties.filter((p) => p.name.trim());
        this.onSubmit(this.listName.trim(), validProps, this.kind);
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
  /**
   * Renders the list of property definition inputs.
   */
  renderProperties(container) {
    container.empty();
    this.properties.forEach((prop, index) => {
      const row = container.createDiv({ cls: "checklist-property-row" });
      new import_obsidian4.Setting(row).setName(`Property ${index + 1}`).addText(
        (text) => text.setPlaceholder("Property name").setValue(prop.name).onChange((value) => {
          this.properties[index].name = value;
        })
      ).addDropdown(
        (dropdown) => dropdown.addOption("text", "Text").addOption("number", "Number").addOption("date", "Date").addOption("checkbox", "Checkbox").addOption("dropdown", "Dropdown").setValue(prop.type).onChange((value) => {
          this.properties[index].type = value;
          this.renderProperties(container);
        })
      ).addButton(
        (button) => button.setIcon("trash").setWarning().onClick(() => {
          this.properties.splice(index, 1);
          this.renderProperties(container);
        })
      );
      new import_obsidian4.Setting(row).setName("Default value").addText(
        (text) => text.setPlaceholder("Optional default").setValue(prop.defaultValue || "").onChange((value) => {
          this.properties[index].defaultValue = value || void 0;
        })
      );
      if (prop.type === "dropdown") {
        new import_obsidian4.Setting(row).setName("Options").setDesc("Comma-separated values").addText(
          (text) => text.setPlaceholder("Option1, Option2, Option3").setValue((prop.options || []).join(", ")).onChange((value) => {
            this.properties[index].options = value.split(",").map((s) => s.trim()).filter(Boolean);
          })
        );
      }
    });
  }
};

// src/modals/AddItemModal.ts
var import_obsidian5 = require("obsidian");
var AddItemModal = class extends import_obsidian5.Modal {
  constructor(app, properties, onSubmit) {
    super(app);
    this.itemName = "";
    this.propertyValues = {};
    this.description = "";
    this.properties = properties;
    this.onSubmit = onSubmit;
    for (const prop of properties) {
      if (prop.defaultValue !== void 0) {
        this.propertyValues[prop.name] = prop.defaultValue;
      }
    }
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("checklist-modal");
    contentEl.createEl("h2", { text: "Add New Item" });
    new import_obsidian5.Setting(contentEl).setName("Name").setDesc("Name for the checklist item (also the filename)").addText(
      (text) => text.setPlaceholder("Item name").onChange((value) => {
        this.itemName = value;
      })
    );
    if (this.properties.length > 0) {
      contentEl.createEl("h3", { text: "Properties" });
    }
    for (const prop of this.properties) {
      this.renderPropertyField(contentEl, prop);
    }
    new import_obsidian5.Setting(contentEl).setName("Description").setDesc("Optional description for the item").addTextArea(
      (text) => text.setPlaceholder("Enter a description...").onChange((value) => {
        this.description = value;
      })
    );
    new import_obsidian5.Setting(contentEl).addButton(
      (button) => button.setButtonText("Add Item").setCta().onClick(() => {
        if (!this.itemName.trim()) {
          new import_obsidian5.Notice("Please enter an item name.");
          return;
        }
        this.onSubmit(
          this.itemName.trim(),
          { ...this.propertyValues },
          this.description.trim()
        );
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
  /**
   * Renders an input field for a single property based on its type.
   */
  renderPropertyField(container, prop) {
    const setting = new import_obsidian5.Setting(container).setName(prop.name);
    switch (prop.type) {
      case "text":
      case "date":
        setting.addText(
          (text) => text.setPlaceholder(prop.type === "date" ? "YYYY-MM-DD" : `Enter ${prop.name}`).setValue(String(this.propertyValues[prop.name] || "")).onChange((value) => {
            this.propertyValues[prop.name] = value;
          })
        );
        break;
      case "number":
        setting.addText(
          (text) => text.setPlaceholder("0").setValue(String(this.propertyValues[prop.name] || "")).onChange((value) => {
            const num = Number(value);
            this.propertyValues[prop.name] = isNaN(num) ? value : num;
          })
        );
        break;
      case "checkbox":
        setting.addToggle(
          (toggle) => toggle.setValue(Boolean(this.propertyValues[prop.name])).onChange((value) => {
            this.propertyValues[prop.name] = value;
          })
        );
        break;
      case "dropdown":
        setting.addDropdown((dropdown) => {
          dropdown.addOption("", `Select ${prop.name}...`);
          for (const option of prop.options || []) {
            dropdown.addOption(option, option);
          }
          dropdown.setValue(String(this.propertyValues[prop.name] || "")).onChange((value) => {
            this.propertyValues[prop.name] = value;
          });
        });
        break;
    }
  }
};

// src/modals/AddItemsModal.ts
var import_obsidian6 = require("obsidian");
var AddItemsModal = class extends import_obsidian6.Modal {
  constructor(app, properties, onSubmit) {
    super(app);
    this.items = [];
    this.properties = properties;
    this.onSubmit = onSubmit;
    this.addEmptyItem();
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("checklist-modal");
    contentEl.createEl("h2", { text: "Add Multiple Items" });
    this.listContainer = contentEl.createDiv({ cls: "checklist-bulk-items" });
    this.renderItems();
    new import_obsidian6.Setting(contentEl).addButton(
      (button) => button.setButtonText("+ Add Another").onClick(() => {
        this.addEmptyItem();
        this.renderItems();
      })
    );
    new import_obsidian6.Setting(contentEl).addButton(
      (button) => button.setButtonText("Add All Items").setCta().onClick(() => {
        const validItems = this.items.filter((item) => item.name.trim());
        if (validItems.length === 0) {
          new import_obsidian6.Notice("Please enter at least one item name.");
          return;
        }
        this.onSubmit(
          validItems.map((item) => ({
            ...item,
            name: item.name.trim(),
            description: item.description.trim()
          }))
        );
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
  addEmptyItem() {
    const item = { name: "", properties: {}, description: "" };
    for (const prop of this.properties) {
      if (prop.defaultValue !== void 0) {
        item.properties[prop.name] = prop.defaultValue;
      }
    }
    this.items.push(item);
  }
  renderItems() {
    this.listContainer.empty();
    for (let i = 0; i < this.items.length; i++) {
      const item = this.items[i];
      const itemDiv = this.listContainer.createDiv({ cls: "checklist-bulk-item" });
      const header = itemDiv.createDiv({ cls: "checklist-bulk-item-header" });
      header.createSpan({ text: `Item ${i + 1}` });
      if (this.items.length > 1) {
        const removeBtn = header.createEl("button", {
          text: "Remove",
          cls: "checklist-btn-remove"
        });
        removeBtn.addEventListener("click", () => {
          this.items.splice(i, 1);
          this.renderItems();
        });
      }
      new import_obsidian6.Setting(itemDiv).setName("Name").addText(
        (text) => text.setPlaceholder("Item name").setValue(item.name).onChange((value) => {
          item.name = value;
        })
      );
      for (const prop of this.properties) {
        this.renderPropertyField(itemDiv, prop, item);
      }
      new import_obsidian6.Setting(itemDiv).setName("Description").addTextArea(
        (text) => text.setPlaceholder("Optional description...").setValue(item.description).onChange((value) => {
          item.description = value;
        })
      );
    }
  }
  renderPropertyField(container, prop, item) {
    const setting = new import_obsidian6.Setting(container).setName(prop.name);
    switch (prop.type) {
      case "text":
      case "date":
        setting.addText(
          (text) => text.setPlaceholder(prop.type === "date" ? "YYYY-MM-DD" : `Enter ${prop.name}`).setValue(String(item.properties[prop.name] || "")).onChange((value) => {
            item.properties[prop.name] = value;
          })
        );
        break;
      case "number":
        setting.addText(
          (text) => text.setPlaceholder("0").setValue(String(item.properties[prop.name] || "")).onChange((value) => {
            const num = Number(value);
            item.properties[prop.name] = isNaN(num) ? value : num;
          })
        );
        break;
      case "checkbox":
        setting.addToggle(
          (toggle) => toggle.setValue(Boolean(item.properties[prop.name])).onChange((value) => {
            item.properties[prop.name] = value;
          })
        );
        break;
      case "dropdown":
        setting.addDropdown((dropdown) => {
          dropdown.addOption("", `Select ${prop.name}...`);
          for (const option of prop.options || []) {
            dropdown.addOption(option, option);
          }
          dropdown.setValue(String(item.properties[prop.name] || "")).onChange((value) => {
            item.properties[prop.name] = value;
          });
        });
        break;
    }
  }
};

// src/modals/ShareToChecklistModal.ts
var import_obsidian7 = require("obsidian");
var ShareToChecklistModal = class extends import_obsidian7.Modal {
  constructor(app, manager, sharedText, onItemAdded) {
    var _a;
    super(app);
    this.itemName = "";
    this.description = "";
    this.selectedChecklistId = "";
    this.manager = manager;
    this.sharedText = sharedText;
    this.onItemAdded = onItemAdded;
    const lines = sharedText.trim().split("\n");
    this.itemName = ((_a = lines[0]) == null ? void 0 : _a.trim()) || "";
    this.description = lines.slice(1).join("\n").trim();
    const activeId = this.manager.getSettings().activeChecklistId;
    if (activeId) {
      this.selectedChecklistId = activeId;
    }
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("checklist-modal");
    contentEl.createEl("h2", { text: "Add to Checklist" });
    const checklists = this.manager.getSettings().checklists;
    if (checklists.length === 0) {
      contentEl.createEl("p", {
        text: "No checklists found. Create one first."
      });
      return;
    }
    new import_obsidian7.Setting(contentEl).setName("Checklist").setDesc("Select the checklist to add the item to").addDropdown((dropdown) => {
      dropdown.addOption("", "Select a checklist...");
      for (const cl of checklists) {
        dropdown.addOption(cl.id, cl.name);
      }
      dropdown.setValue(this.selectedChecklistId).onChange((value) => {
        this.selectedChecklistId = value;
      });
    });
    new import_obsidian7.Setting(contentEl).setName("Name").setDesc("Name for the checklist item").addText(
      (text) => text.setPlaceholder("Item name").setValue(this.itemName).onChange((value) => {
        this.itemName = value;
      })
    );
    new import_obsidian7.Setting(contentEl).setName("Description").setDesc("Optional description for the item").addTextArea(
      (text) => text.setPlaceholder("Enter a description...").setValue(this.description).onChange((value) => {
        this.description = value;
      })
    );
    new import_obsidian7.Setting(contentEl).addButton(
      (button) => button.setButtonText("Add to Checklist").setCta().onClick(async () => {
        if (!this.selectedChecklistId) {
          new import_obsidian7.Notice("Please select a checklist.");
          return;
        }
        if (!this.itemName.trim()) {
          new import_obsidian7.Notice("Please enter an item name.");
          return;
        }
        await this.manager.addItem(
          this.selectedChecklistId,
          this.itemName.trim(),
          {},
          this.description.trim()
        );
        new import_obsidian7.Notice(`Item "${this.itemName.trim()}" added.`);
        this.onItemAdded(this.selectedChecklistId);
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/views/ChecklistSettingTab.ts
var import_obsidian8 = require("obsidian");

// src/models/types.ts
var DEFAULT_CHECKLISTS_FOLDER = "checklists";
var DEFAULT_SETTINGS = {
  checklists: [],
  activeChecklistId: null,
  checklistsFolder: DEFAULT_CHECKLISTS_FOLDER
};

// src/views/ChecklistSettingTab.ts
var ChecklistSettingTab = class extends import_obsidian8.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    let pendingFolder = this.plugin.settings.checklistsFolder;
    new import_obsidian8.Setting(containerEl).setName("Checklists folder").setDesc(
      "The main folder where checklists are stored. New checklists will be created as subfolders of this folder."
    ).addText(
      (text) => text.setPlaceholder(DEFAULT_CHECKLISTS_FOLDER).setValue(this.plugin.settings.checklistsFolder).onChange((value) => {
        pendingFolder = value;
      })
    ).addButton(
      (button) => button.setButtonText("Save").setCta().onClick(async () => {
        const previousFolder = this.plugin.settings.checklistsFolder;
        const trimmed = pendingFolder.trim().replace(/^\/+|\/+$/g, "");
        this.plugin.settings.checklistsFolder = trimmed || DEFAULT_CHECKLISTS_FOLDER;
        await this.plugin.saveSettings();
        if (this.plugin.settings.checklistsFolder !== previousFolder && typeof this.plugin.onChecklistsFolderUpdated === "function") {
          await this.plugin.onChecklistsFolderUpdated();
        }
        new import_obsidian8.Notice("Checklists folder saved.");
      })
    );
  }
};

// src/main.ts
var ChecklistPlugin = class extends import_obsidian9.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.manager = new ChecklistManager(
      this.app,
      this.settings,
      () => this.saveSettings()
    );
    this.addSettingTab(new ChecklistSettingTab(this.app, this));
    this.registerView(VIEW_TYPE_CHECKLIST_SIDEBAR, (leaf) => {
      return new ChecklistSidebarView(
        leaf,
        this.manager,
        (id) => this.selectChecklist(id),
        () => this.openCreateListModal(),
        (id) => this.handleDeleteChecklist(id),
        (id, format) => this.handleExport(id, format)
      );
    });
    this.registerView(VIEW_TYPE_CHECKLIST, (leaf) => {
      return new ChecklistView(
        leaf,
        this.manager,
        () => this.openAddItemModal(),
        () => this.openAddItemsModal(),
        (filePath) => this.handleDeleteItem(filePath),
        () => this.refreshSidebar(),
        (format) => {
          const active = this.manager.getActiveChecklist();
          if (active)
            this.handleExport(active.id, format);
        }
      );
    });
    await this.ensureSidebarEntry();
    this.addRibbonIcon(ICON_CHECKLIST, "Open Checklist", () => {
      this.activateSidebar();
    });
    this.registerShareIntent();
    this.addCommand({
      id: "open-checklist-sidebar",
      name: "Open checklist sidebar",
      callback: () => this.activateSidebar()
    });
    this.addCommand({
      id: "open-checklist-view",
      name: "Open checklist view",
      callback: () => this.activateMainView()
    });
    this.addCommand({
      id: "create-new-checklist",
      name: "Create new checklist",
      callback: () => this.openCreateListModal()
    });
    this.addCommand({
      id: "add-checklist-item",
      name: "Add item to active checklist",
      callback: () => this.openAddItemModal()
    });
    this.addCommand({
      id: "add-checklist-items",
      name: "Add multiple items to active checklist",
      callback: () => this.openAddItemsModal()
    });
    this.addCommand({
      id: "export-checklist-markdown",
      name: "Export active checklist as Markdown",
      callback: () => {
        const active = this.manager.getActiveChecklist();
        if (active)
          this.handleExport(active.id, "markdown");
        else
          new import_obsidian9.Notice("No active checklist.");
      }
    });
    this.addCommand({
      id: "export-checklist-json",
      name: "Export active checklist as JSON",
      callback: () => {
        const active = this.manager.getActiveChecklist();
        if (active)
          this.handleExport(active.id, "json");
        else
          new import_obsidian9.Notice("No active checklist.");
      }
    });
    this.addCommand({
      id: "export-all-checklists-markdown",
      name: "Export all checklists as Markdown",
      callback: () => this.handleExport(null, "markdown")
    });
    this.addCommand({
      id: "export-all-checklists-json",
      name: "Export all checklists as JSON",
      callback: () => this.handleExport(null, "json")
    });
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_CHECKLIST);
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_CHECKLIST_SIDEBAR);
  }
  /**
   * Opens the sidebar in the left panel.
   */
  async activateSidebar() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_CHECKLIST_SIDEBAR);
    if (leaves.length > 0) {
      this.app.workspace.revealLeaf(leaves[0]);
      return;
    }
    const leaf = this.app.workspace.getLeftLeaf(false);
    if (leaf) {
      await leaf.setViewState({
        type: VIEW_TYPE_CHECKLIST_SIDEBAR,
        active: true
      });
      this.app.workspace.revealLeaf(leaf);
    }
  }
  /**
   * Opens the main checklist view.
   */
  async activateMainView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_CHECKLIST);
    if (leaves.length > 0) {
      this.app.workspace.revealLeaf(leaves[0]);
      return;
    }
    const leaf = this.app.workspace.getLeaf(false);
    if (leaf) {
      await leaf.setViewState({
        type: VIEW_TYPE_CHECKLIST,
        active: true
      });
      this.app.workspace.revealLeaf(leaf);
    }
  }
  async ensureSidebarEntry() {
    const sidebarLeaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_CHECKLIST_SIDEBAR);
    if (sidebarLeaves.length > 0)
      return;
    const leaf = this.app.workspace.getLeftLeaf(false);
    if (!leaf)
      return;
    await leaf.setViewState({
      type: VIEW_TYPE_CHECKLIST_SIDEBAR,
      active: false
    });
  }
  /**
   * Selects a checklist from the sidebar, sets it active, and opens the main view.
   */
  async selectChecklist(id) {
    this.manager.setActiveChecklist(id);
    await this.activateMainView();
    this.refreshMainView();
    this.refreshSidebar();
  }
  /**
   * Handles checklist deletion with confirmation.
   */
  async handleDeleteChecklist(id) {
    const checklist = this.manager.getSettings().checklists.find((c) => c.id === id);
    if (!checklist)
      return;
    await this.manager.deleteChecklist(id);
    new import_obsidian9.Notice(`Checklist "${checklist.name}" deleted.`);
    this.refreshSidebar();
    this.refreshMainView();
  }
  /**
   * Handles item deletion.
   */
  async handleDeleteItem(filePath) {
    var _a;
    await this.manager.deleteItem(filePath);
    const name = ((_a = filePath.split("/").pop()) == null ? void 0 : _a.replace(/\.md$/, "")) || "Item";
    new import_obsidian9.Notice(`"${name}" deleted.`);
    this.refreshMainView();
    this.refreshSidebar();
  }
  /**
   * Exports a checklist (or all checklists) and saves to vault.
   */
  async handleExport(id, format) {
    const ext = format === "markdown" ? "md" : "json";
    if (id === null) {
      const content = format === "markdown" ? await this.manager.exportAllAsMarkdown() : await this.manager.exportAllAsJson();
      if (!content || content === "") {
        new import_obsidian9.Notice("No checklists to export.");
        return;
      }
      const filePath = `checklists-export.${ext}`;
      await this.saveExportFile(filePath, content);
      new import_obsidian9.Notice(`All checklists exported to ${filePath}`);
    } else {
      const checklist = this.manager.getSettings().checklists.find((c) => c.id === id);
      if (!checklist)
        return;
      const content = format === "markdown" ? await this.manager.exportChecklistAsMarkdown(id) : await this.manager.exportChecklistAsJson(id);
      const safeName = checklist.name.replace(/[\\/:*?"<>|]/g, "-");
      const filePath = `${safeName}-export.${ext}`;
      await this.saveExportFile(filePath, content);
      new import_obsidian9.Notice(`"${checklist.name}" exported to ${filePath}`);
    }
  }
  async saveExportFile(filePath, content) {
    const existing = this.app.vault.getAbstractFileByPath(filePath);
    if (existing) {
      await this.app.vault.modify(existing, content);
    } else {
      await this.app.vault.create(filePath, content);
    }
  }
  openCreateListModal() {
    new CreateListModal(this.app, async (name, properties, kind) => {
      await this.manager.createChecklist(name, properties, kind);
      new import_obsidian9.Notice(`${kind === "list" ? "List" : "Checklist"} "${name}" created.`);
      this.refreshSidebar();
      await this.activateMainView();
      this.refreshMainView();
    }).open();
  }
  openAddItemModal() {
    const active = this.manager.getActiveChecklist();
    if (!active) {
      new import_obsidian9.Notice("No active checklist. Create one first.");
      return;
    }
    new AddItemModal(
      this.app,
      active.properties,
      async (name, properties, description) => {
        await this.manager.addItem(active.id, name, properties, description);
        new import_obsidian9.Notice(`Item "${name}" added.`);
        this.refreshMainView();
        this.refreshSidebar();
      }
    ).open();
  }
  openAddItemsModal() {
    const active = this.manager.getActiveChecklist();
    if (!active) {
      new import_obsidian9.Notice("No active checklist. Create one first.");
      return;
    }
    new AddItemsModal(
      this.app,
      active.properties,
      async (items) => {
        const files = await this.manager.addItems(active.id, items);
        new import_obsidian9.Notice(`${files.length} item(s) added.`);
        this.refreshMainView();
        this.refreshSidebar();
      }
    ).open();
  }
  refreshMainView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_CHECKLIST);
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof ChecklistView) {
        view.renderView();
      }
    }
  }
  refreshSidebar() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_CHECKLIST_SIDEBAR);
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof ChecklistSidebarView) {
        view.renderView();
      }
    }
  }
  registerShareIntent() {
    this.registerObsidianProtocolHandler("checklist-add", async (params) => {
      const text = params.text || params.url || "";
      if (text) {
        this.openShareModal(text);
      }
    });
    try {
      if (this.app.isMobile) {
        const addToChecklistMenuItem = (menu, text) => {
          menu.addItem((item) => {
            item.setTitle("Add to Checklist").setIcon(ICON_CHECKLIST).onClick(() => {
              this.openShareModal(text);
            });
          });
        };
        this.registerEvent(
          // @ts-ignore
          this.app.workspace.on("receive-text-menu", addToChecklistMenuItem)
        );
        this.registerEvent(
          // @ts-ignore
          this.app.workspace.on("receive-url-menu", addToChecklistMenuItem)
        );
      }
    } catch (e) {
    }
  }
  openShareModal(sharedText) {
    new ShareToChecklistModal(
      this.app,
      this.manager,
      sharedText,
      (checklistId) => {
        this.manager.setActiveChecklist(checklistId);
        this.refreshMainView();
        this.refreshSidebar();
      }
    ).open();
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
    for (const c of this.settings.checklists) {
      if (!c.kind)
        c.kind = "checklist";
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async onChecklistsFolderUpdated() {
    await this.manager.syncChecklistsFromFolder(this.settings.checklistsFolder);
    this.refreshSidebar();
    this.refreshMainView();
  }
};
