/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ChecklistPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/constants.ts
var VIEW_TYPE_CHECKLIST = "checklist-view";
var VIEW_TYPE_CHECKLIST_SIDEBAR = "checklist-sidebar";
var ICON_CHECKLIST = "check-square";

// src/views/ChecklistView.ts
var import_obsidian = require("obsidian");
var ChecklistView = class extends import_obsidian.ItemView {
  constructor(leaf, manager, onAddItem, onAddItems, onDeleteItem, onRefreshSidebar, onExport) {
    super(leaf);
    this.manager = manager;
    this.onAddItem = onAddItem;
    this.onAddItems = onAddItems;
    this.onDeleteItem = onDeleteItem;
    this.onRefreshSidebar = onRefreshSidebar;
    this.onExport = onExport;
    this.contentContainer = document.createElement("div");
  }
  getViewType() {
    return VIEW_TYPE_CHECKLIST;
  }
  getDisplayText() {
    const active = this.manager.getActiveChecklist();
    return active ? active.name : "Checklist";
  }
  getIcon() {
    return ICON_CHECKLIST;
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("checklist-view-container");
    this.contentContainer = container.createDiv({ cls: "checklist-content" });
    await this.renderView();
  }
  async onClose() {
    this.contentContainer.empty();
  }
  async renderView() {
    this.contentContainer.empty();
    const activeChecklist = this.manager.getActiveChecklist();
    if (!activeChecklist) {
      this.renderEmptyState();
      return;
    }
    await this.renderItems(activeChecklist);
    this.renderFAB();
  }
  renderEmptyState() {
    const emptyDiv = this.contentContainer.createDiv({ cls: "checklist-empty" });
    emptyDiv.createEl("p", {
      text: "Select a checklist from the sidebar to view items.",
      cls: "checklist-empty-text"
    });
  }
  async renderItems(checklist) {
    const titleBar = this.contentContainer.createDiv({ cls: "checklist-title-bar" });
    titleBar.createEl("h4", { text: checklist.name, cls: "checklist-title" });
    const exportBtn = titleBar.createEl("button", {
      cls: "checklist-export-btn clickable-icon",
      attr: { "aria-label": "Export checklist" }
    });
    (0, import_obsidian.setIcon)(exportBtn, "download");
    exportBtn.addEventListener("click", (e) => {
      const menu = new import_obsidian.Menu();
      menu.addItem((item) => {
        item.setTitle("Export as Markdown").setIcon("file-text").onClick(() => this.onExport("markdown"));
      });
      menu.addItem((item) => {
        item.setTitle("Export as JSON").setIcon("braces").onClick(() => this.onExport("json"));
      });
      menu.showAtMouseEvent(e);
    });
    const items = await this.manager.getItems(checklist.id);
    const listContainer = this.contentContainer.createDiv({ cls: "checklist-items" });
    if (items.length === 0) {
      listContainer.createEl("p", {
        text: "No items yet. Add one to get started!",
        cls: "checklist-no-items"
      });
    } else {
      const headerRow = listContainer.createDiv({ cls: "checklist-header-row" });
      headerRow.createDiv({ cls: "checklist-col checklist-col-check", text: "" });
      headerRow.createDiv({ cls: "checklist-col checklist-col-name", text: "Name" });
      for (const prop of checklist.properties) {
        headerRow.createDiv({ cls: "checklist-col checklist-col-prop", text: prop.name });
      }
      headerRow.createDiv({ cls: "checklist-col checklist-col-actions", text: "" });
      for (const item of items) {
        this.renderItem(listContainer, item, checklist);
      }
    }
    this.renderInlineAdd(listContainer, checklist);
  }
  renderItem(container, item, checklist) {
    const row = container.createDiv({ cls: "checklist-item-row" });
    const checkCell = row.createDiv({ cls: "checklist-col checklist-col-check" });
    const checkbox = checkCell.createEl("input", { type: "checkbox" });
    checkbox.checked = item.completed;
    checkbox.addEventListener("change", async () => {
      if (checkbox.checked) {
        row.addClass("checklist-item-completing");
        setTimeout(async () => {
          await this.manager.completeItem(item.filePath);
          await this.renderView();
          this.onRefreshSidebar();
        }, 300);
      }
    });
    const nameCell = row.createDiv({ cls: "checklist-col checklist-col-name" });
    nameCell.createSpan({ text: item.name, cls: "checklist-item-name" });
    if (item.description) {
      nameCell.createEl("small", {
        text: item.description,
        cls: "checklist-item-desc"
      });
    }
    for (const prop of checklist.properties) {
      const value = item.properties[prop.name] || "";
      row.createDiv({
        cls: "checklist-col checklist-col-prop",
        text: String(value)
      });
    }
    const actionsCell = row.createDiv({ cls: "checklist-col checklist-col-actions" });
    const deleteBtn = actionsCell.createEl("button", {
      cls: "checklist-item-delete clickable-icon",
      attr: { "aria-label": "Delete item" }
    });
    (0, import_obsidian.setIcon)(deleteBtn, "trash-2");
    deleteBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.onDeleteItem(item.filePath);
    });
    row.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      const menu = new import_obsidian.Menu();
      menu.addItem((menuItem) => {
        menuItem.setTitle("Delete item").setIcon("trash-2").onClick(() => this.onDeleteItem(item.filePath));
      });
      menu.showAtMouseEvent(e);
    });
  }
  renderInlineAdd(container, checklist) {
    const inlineRow = container.createDiv({ cls: "checklist-inline-add" });
    const iconEl = inlineRow.createSpan({ cls: "checklist-inline-add-icon" });
    (0, import_obsidian.setIcon)(iconEl, "plus");
    const input = inlineRow.createEl("input", {
      type: "text",
      cls: "checklist-inline-add-input",
      attr: { placeholder: "Add new item..." }
    });
    input.addEventListener("keydown", async (e) => {
      if (e.key === "Enter" && input.value.trim()) {
        const name = input.value.trim();
        await this.manager.addItem(checklist.id, name, {}, "");
        input.value = "";
        await this.renderView();
        this.onRefreshSidebar();
      }
    });
  }
  renderFAB() {
    const fab = this.contentContainer.createDiv({ cls: "checklist-fab" });
    const mainBtn = fab.createEl("button", {
      cls: "checklist-fab-main",
      attr: { "aria-label": "Add items" }
    });
    (0, import_obsidian.setIcon)(mainBtn, "plus");
    const fabMenu = fab.createDiv({ cls: "checklist-fab-menu" });
    const addOneBtn = fabMenu.createEl("button", {
      cls: "checklist-fab-option",
      attr: { "aria-label": "Add single item" }
    });
    (0, import_obsidian.setIcon)(addOneBtn, "plus");
    addOneBtn.createSpan({ text: "Add Item" });
    addOneBtn.addEventListener("click", () => {
      fab.removeClass("is-open");
      this.onAddItem();
    });
    const addMultiBtn = fabMenu.createEl("button", {
      cls: "checklist-fab-option",
      attr: { "aria-label": "Add multiple items" }
    });
    (0, import_obsidian.setIcon)(addMultiBtn, "list-plus");
    addMultiBtn.createSpan({ text: "Add Multiple" });
    addMultiBtn.addEventListener("click", () => {
      fab.removeClass("is-open");
      this.onAddItems();
    });
    mainBtn.addEventListener("click", () => {
      fab.toggleClass("is-open", !fab.hasClass("is-open"));
    });
  }
};

// src/views/ChecklistSidebarView.ts
var import_obsidian2 = require("obsidian");
var ChecklistSidebarView = class extends import_obsidian2.ItemView {
  constructor(leaf, manager, onSelectChecklist, onCreateList, onDeleteChecklist, onExport) {
    super(leaf);
    this.manager = manager;
    this.onSelectChecklist = onSelectChecklist;
    this.onCreateList = onCreateList;
    this.onDeleteChecklist = onDeleteChecklist;
    this.onExport = onExport;
    this.contentContainer = document.createElement("div");
  }
  getViewType() {
    return VIEW_TYPE_CHECKLIST_SIDEBAR;
  }
  getDisplayText() {
    return "Checklists";
  }
  getIcon() {
    return ICON_CHECKLIST;
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("checklist-sidebar-container");
    this.contentContainer = container.createDiv({ cls: "checklist-sidebar-content" });
    await this.renderView();
  }
  async onClose() {
    this.contentContainer.empty();
  }
  async renderView() {
    this.contentContainer.empty();
    const header = this.contentContainer.createDiv({ cls: "checklist-sidebar-header" });
    header.createSpan({ text: "Checklists", cls: "checklist-sidebar-title" });
    const headerActions = header.createDiv({ cls: "checklist-sidebar-header-actions" });
    const exportBtn = headerActions.createEl("button", {
      cls: "checklist-sidebar-add-btn clickable-icon",
      attr: { "aria-label": "Export all checklists" }
    });
    (0, import_obsidian2.setIcon)(exportBtn, "download");
    exportBtn.addEventListener("click", (e) => {
      const menu = new import_obsidian2.Menu();
      menu.addItem((item) => {
        item.setTitle("Export all as Markdown").setIcon("file-text").onClick(() => this.onExport(null, "markdown"));
      });
      menu.addItem((item) => {
        item.setTitle("Export all as JSON").setIcon("braces").onClick(() => this.onExport(null, "json"));
      });
      menu.showAtMouseEvent(e);
    });
    const addBtn = headerActions.createEl("button", {
      cls: "checklist-sidebar-add-btn clickable-icon",
      attr: { "aria-label": "New checklist" }
    });
    (0, import_obsidian2.setIcon)(addBtn, "plus");
    addBtn.addEventListener("click", () => this.onCreateList());
    const checklists = this.manager.getSettings().checklists;
    const activeId = this.manager.getSettings().activeChecklistId;
    if (checklists.length === 0) {
      const empty = this.contentContainer.createDiv({ cls: "checklist-sidebar-empty" });
      empty.createEl("p", { text: "No checklists yet." });
      return;
    }
    const list = this.contentContainer.createDiv({ cls: "checklist-sidebar-list" });
    for (const checklist of checklists) {
      this.renderChecklistEntry(list, checklist, checklist.id === activeId);
    }
  }
  renderChecklistEntry(container, checklist, isActive) {
    const entry = container.createDiv({
      cls: `checklist-sidebar-entry${isActive ? " is-active" : ""}`
    });
    const iconEl = entry.createSpan({ cls: "checklist-sidebar-entry-icon" });
    (0, import_obsidian2.setIcon)(iconEl, ICON_CHECKLIST);
    entry.createSpan({
      text: checklist.name,
      cls: "checklist-sidebar-entry-name"
    });
    const countEl = entry.createSpan({ cls: "checklist-sidebar-entry-count" });
    this.manager.getItems(checklist.id).then((items) => {
      countEl.setText(String(items.length));
    });
    entry.addEventListener("click", () => {
      this.onSelectChecklist(checklist.id);
    });
    entry.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      const menu = new import_obsidian2.Menu();
      menu.addItem((item) => {
        item.setTitle("Export as Markdown").setIcon("file-text").onClick(() => this.onExport(checklist.id, "markdown"));
      });
      menu.addItem((item) => {
        item.setTitle("Export as JSON").setIcon("braces").onClick(() => this.onExport(checklist.id, "json"));
      });
      menu.addItem((item) => {
        item.setTitle("Delete checklist").setIcon("trash").onClick(() => this.onDeleteChecklist(checklist.id));
      });
      menu.showAtMouseEvent(e);
    });
  }
};

// src/services/ChecklistManager.ts
var import_obsidian3 = require("obsidian");

// src/utils/frontmatter.ts
function needsQuoting(value) {
  return value.includes(":") || value.includes("#") || value.includes("'") || value.includes('"') || value.includes("\n") || value.startsWith(" ") || value.endsWith(" ") || value === "true" || value === "false" || value === "null" || /^\d{4}-\d{2}-\d{2}/.test(value);
}
function formatYamlValue(value) {
  if (typeof value === "boolean" || typeof value === "number") {
    return String(value);
  }
  if (needsQuoting(value)) {
    return `"${value.replace(/"/g, '\\"')}"`;
  }
  return value;
}
function generateFrontmatter(properties) {
  const lines = ["---"];
  for (const [key, value] of Object.entries(properties)) {
    lines.push(`${key}: ${formatYamlValue(value)}`);
  }
  if (!("completed" in properties)) {
    lines.push("completed: false");
  }
  lines.push("---");
  return lines.join("\n");
}
function parseFrontmatter(content) {
  const trimmed = content.trim();
  if (!trimmed.startsWith("---")) {
    return { properties: {}, body: trimmed };
  }
  const lines = trimmed.split("\n");
  let endIndex = -1;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i].trim() === "---") {
      endIndex = i;
      break;
    }
  }
  if (endIndex === -1) {
    return { properties: {}, body: trimmed };
  }
  const properties = {};
  for (let i = 1; i < endIndex; i++) {
    const line = lines[i];
    const colonIndex = line.indexOf(":");
    if (colonIndex === -1)
      continue;
    const key = line.substring(0, colonIndex).trim();
    let value = line.substring(colonIndex + 1).trim();
    if (value.startsWith('"') && value.endsWith('"') || value.startsWith("'") && value.endsWith("'")) {
      value = value.slice(1, -1);
    }
    properties[key] = value;
  }
  const bodyLines = lines.slice(endIndex + 1);
  const body = bodyLines.join("\n").trim();
  return { properties, body };
}

// src/services/ChecklistManager.ts
function generateId() {
  return Date.now().toString(36) + Math.random().toString(36).substring(2, 8);
}
var ChecklistManager = class {
  constructor(app, settings, save) {
    this.app = app;
    this.settings = settings;
    this.save = save;
  }
  getSettings() {
    return this.settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  /**
   * Creates a new checklist definition and its folder.
   */
  async createChecklist(name, properties) {
    const folderPath = `checklists/${name}`;
    const checklist = {
      id: generateId(),
      name,
      folderPath,
      properties,
      createdAt: (/* @__PURE__ */ new Date()).toISOString()
    };
    this.settings.checklists.push(checklist);
    this.settings.activeChecklistId = checklist.id;
    await this.app.vault.createFolder(folderPath);
    await this.save();
    return checklist;
  }
  /**
   * Deletes a checklist definition from settings and removes all its item files.
   */
  async deleteChecklist(id) {
    const checklist = this.settings.checklists.find((c) => c.id === id);
    if (checklist) {
      const allFiles = this.app.vault.getMarkdownFiles();
      const checklistFiles = allFiles.filter(
        (f) => f.path.startsWith(checklist.folderPath + "/")
      );
      for (const file of checklistFiles) {
        await this.app.vault.delete(file);
      }
    }
    this.settings.checklists = this.settings.checklists.filter((c) => c.id !== id);
    if (this.settings.activeChecklistId === id) {
      this.settings.activeChecklistId = null;
    }
    await this.save();
  }
  /**
   * Deletes a single item (markdown file) by its file path.
   */
  async deleteItem(filePath) {
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (file instanceof import_obsidian3.TFile) {
      await this.app.vault.delete(file);
    } else {
      await this.app.vault.delete({ path: filePath });
    }
  }
  /**
   * Adds a new item (markdown file) to a checklist folder.
   */
  async addItem(checklistId, name, properties, description) {
    const [file] = await this.addItems(checklistId, [{ name, properties, description }]);
    return file;
  }
  /**
   * Adds multiple items (markdown files) to a checklist folder at once.
   */
  async addItems(checklistId, items) {
    if (items.length === 0)
      return [];
    const checklist = this.findChecklist(checklistId);
    const files = [];
    for (const item of items) {
      const mergedProperties = this.mergeProperties(checklist.properties, item.properties);
      const frontmatter = generateFrontmatter(mergedProperties);
      const content = item.description ? `${frontmatter}

${item.description}` : `${frontmatter}
`;
      const filePath = `${checklist.folderPath}/${item.name}.md`;
      const file = await this.app.vault.create(filePath, content);
      files.push(file);
    }
    return files;
  }
  /**
   * Merges provided properties with defaults from property definitions.
   */
  mergeProperties(definitions, properties) {
    const merged = {};
    for (const prop of definitions) {
      if (prop.name in properties) {
        merged[prop.name] = properties[prop.name];
      } else if (prop.defaultValue !== void 0) {
        merged[prop.name] = prop.defaultValue;
      }
    }
    for (const [key, value] of Object.entries(properties)) {
      if (!(key in merged)) {
        merged[key] = value;
      }
    }
    return merged;
  }
  /**
   * Marks an item as complete by deleting its file.
   */
  async completeItem(filePath) {
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (file instanceof import_obsidian3.TFile) {
      await this.app.vault.delete(file);
    } else {
      await this.app.vault.delete({ path: filePath });
    }
  }
  /**
   * Reads all items from a checklist's folder.
   */
  async getItems(checklistId) {
    const checklist = this.findChecklist(checklistId);
    const allFiles = this.app.vault.getMarkdownFiles();
    const checklistFiles = allFiles.filter(
      (f) => f.path.startsWith(checklist.folderPath + "/")
    );
    const items = [];
    for (const file of checklistFiles) {
      const content = await this.app.vault.read(file);
      const parsed = parseFrontmatter(content);
      items.push({
        filePath: file.path,
        name: file.basename,
        description: parsed.body,
        properties: parsed.properties,
        completed: parsed.properties["completed"] === "true"
      });
    }
    return items;
  }
  /**
   * Returns the active checklist definition, or null.
   */
  getActiveChecklist() {
    if (!this.settings.activeChecklistId)
      return null;
    return this.settings.checklists.find(
      (c) => c.id === this.settings.activeChecklistId
    ) || null;
  }
  /**
   * Sets the active checklist by ID.
   */
  setActiveChecklist(id) {
    this.settings.activeChecklistId = id;
    this.save();
  }
  /**
   * Exports a single checklist as a markdown string.
   */
  async exportChecklistAsMarkdown(checklistId) {
    const checklist = this.findChecklist(checklistId);
    const items = await this.getItems(checklistId);
    const lines = [`# ${checklist.name}`, ""];
    for (const item of items) {
      const status = item.completed ? "x" : " ";
      lines.push(`- [${status}] ${item.name}`);
      for (const prop of checklist.properties) {
        const val = item.properties[prop.name];
        if (val !== void 0 && val !== "") {
          lines.push(`  - ${prop.name}: ${val}`);
        }
      }
      if (item.description) {
        lines.push(`  - ${item.description}`);
      }
    }
    return lines.join("\n") + "\n";
  }
  /**
   * Exports a single checklist as a JSON string.
   */
  async exportChecklistAsJson(checklistId) {
    const checklist = this.findChecklist(checklistId);
    const items = await this.getItems(checklistId);
    const data = {
      name: checklist.name,
      properties: checklist.properties,
      items: items.map((item) => ({
        name: item.name,
        properties: item.properties,
        description: item.description,
        completed: item.completed
      }))
    };
    return JSON.stringify(data, null, 2);
  }
  /**
   * Exports all checklists as a combined markdown string.
   */
  async exportAllAsMarkdown() {
    const checklists = this.settings.checklists;
    if (checklists.length === 0)
      return "";
    const sections = [];
    for (const checklist of checklists) {
      sections.push(await this.exportChecklistAsMarkdown(checklist.id));
    }
    return sections.join("\n");
  }
  /**
   * Exports all checklists as a JSON string.
   */
  async exportAllAsJson() {
    const checklists = this.settings.checklists;
    const allData = [];
    for (const checklist of checklists) {
      const items = await this.getItems(checklist.id);
      allData.push({
        name: checklist.name,
        properties: checklist.properties,
        items: items.map((item) => ({
          name: item.name,
          properties: item.properties,
          description: item.description,
          completed: item.completed
        }))
      });
    }
    return JSON.stringify({ checklists: allData }, null, 2);
  }
  /**
   * Finds a checklist by ID or throws.
   */
  findChecklist(id) {
    const checklist = this.settings.checklists.find((c) => c.id === id);
    if (!checklist) {
      throw new Error("Checklist not found");
    }
    return checklist;
  }
};

// src/modals/CreateListModal.ts
var import_obsidian4 = require("obsidian");
var CreateListModal = class extends import_obsidian4.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.listName = "";
    this.properties = [];
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("checklist-modal");
    contentEl.createEl("h2", { text: "Create New Checklist" });
    new import_obsidian4.Setting(contentEl).setName("Checklist name").setDesc("Name for the new checklist").addText(
      (text) => text.setPlaceholder("My Tasks").onChange((value) => {
        this.listName = value;
      })
    );
    contentEl.createEl("h3", { text: "Properties" });
    contentEl.createEl("p", {
      text: "Define the front matter fields for each item in this checklist.",
      cls: "setting-item-description"
    });
    const propertiesContainer = contentEl.createDiv({ cls: "checklist-properties-list" });
    this.renderProperties(propertiesContainer);
    new import_obsidian4.Setting(contentEl).addButton(
      (button) => button.setButtonText("Add Property").onClick(() => {
        this.properties.push({
          name: "",
          type: "text"
        });
        this.renderProperties(propertiesContainer);
      })
    );
    new import_obsidian4.Setting(contentEl).addButton(
      (button) => button.setButtonText("Create Checklist").setCta().onClick(() => {
        if (!this.listName.trim()) {
          new import_obsidian4.Notice("Please enter a checklist name.");
          return;
        }
        const validProps = this.properties.filter((p) => p.name.trim());
        this.onSubmit(this.listName.trim(), validProps);
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
  /**
   * Renders the list of property definition inputs.
   */
  renderProperties(container) {
    container.empty();
    this.properties.forEach((prop, index) => {
      const row = container.createDiv({ cls: "checklist-property-row" });
      new import_obsidian4.Setting(row).setName(`Property ${index + 1}`).addText(
        (text) => text.setPlaceholder("Property name").setValue(prop.name).onChange((value) => {
          this.properties[index].name = value;
        })
      ).addDropdown(
        (dropdown) => dropdown.addOption("text", "Text").addOption("number", "Number").addOption("date", "Date").addOption("checkbox", "Checkbox").addOption("dropdown", "Dropdown").setValue(prop.type).onChange((value) => {
          this.properties[index].type = value;
          this.renderProperties(container);
        })
      ).addButton(
        (button) => button.setIcon("trash").setWarning().onClick(() => {
          this.properties.splice(index, 1);
          this.renderProperties(container);
        })
      );
      new import_obsidian4.Setting(row).setName("Default value").addText(
        (text) => text.setPlaceholder("Optional default").setValue(prop.defaultValue || "").onChange((value) => {
          this.properties[index].defaultValue = value || void 0;
        })
      );
      if (prop.type === "dropdown") {
        new import_obsidian4.Setting(row).setName("Options").setDesc("Comma-separated values").addText(
          (text) => text.setPlaceholder("Option1, Option2, Option3").setValue((prop.options || []).join(", ")).onChange((value) => {
            this.properties[index].options = value.split(",").map((s) => s.trim()).filter(Boolean);
          })
        );
      }
    });
  }
};

// src/modals/AddItemModal.ts
var import_obsidian5 = require("obsidian");
var AddItemModal = class extends import_obsidian5.Modal {
  constructor(app, properties, onSubmit) {
    super(app);
    this.itemName = "";
    this.propertyValues = {};
    this.description = "";
    this.properties = properties;
    this.onSubmit = onSubmit;
    for (const prop of properties) {
      if (prop.defaultValue !== void 0) {
        this.propertyValues[prop.name] = prop.defaultValue;
      }
    }
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("checklist-modal");
    contentEl.createEl("h2", { text: "Add New Item" });
    new import_obsidian5.Setting(contentEl).setName("Name").setDesc("Name for the checklist item (also the filename)").addText(
      (text) => text.setPlaceholder("Item name").onChange((value) => {
        this.itemName = value;
      })
    );
    if (this.properties.length > 0) {
      contentEl.createEl("h3", { text: "Properties" });
    }
    for (const prop of this.properties) {
      this.renderPropertyField(contentEl, prop);
    }
    new import_obsidian5.Setting(contentEl).setName("Description").setDesc("Optional description for the item").addTextArea(
      (text) => text.setPlaceholder("Enter a description...").onChange((value) => {
        this.description = value;
      })
    );
    new import_obsidian5.Setting(contentEl).addButton(
      (button) => button.setButtonText("Add Item").setCta().onClick(() => {
        if (!this.itemName.trim()) {
          new import_obsidian5.Notice("Please enter an item name.");
          return;
        }
        this.onSubmit(
          this.itemName.trim(),
          { ...this.propertyValues },
          this.description.trim()
        );
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
  /**
   * Renders an input field for a single property based on its type.
   */
  renderPropertyField(container, prop) {
    const setting = new import_obsidian5.Setting(container).setName(prop.name);
    switch (prop.type) {
      case "text":
      case "date":
        setting.addText(
          (text) => text.setPlaceholder(prop.type === "date" ? "YYYY-MM-DD" : `Enter ${prop.name}`).setValue(String(this.propertyValues[prop.name] || "")).onChange((value) => {
            this.propertyValues[prop.name] = value;
          })
        );
        break;
      case "number":
        setting.addText(
          (text) => text.setPlaceholder("0").setValue(String(this.propertyValues[prop.name] || "")).onChange((value) => {
            const num = Number(value);
            this.propertyValues[prop.name] = isNaN(num) ? value : num;
          })
        );
        break;
      case "checkbox":
        setting.addToggle(
          (toggle) => toggle.setValue(Boolean(this.propertyValues[prop.name])).onChange((value) => {
            this.propertyValues[prop.name] = value;
          })
        );
        break;
      case "dropdown":
        setting.addDropdown((dropdown) => {
          dropdown.addOption("", `Select ${prop.name}...`);
          for (const option of prop.options || []) {
            dropdown.addOption(option, option);
          }
          dropdown.setValue(String(this.propertyValues[prop.name] || "")).onChange((value) => {
            this.propertyValues[prop.name] = value;
          });
        });
        break;
    }
  }
};

// src/modals/AddItemsModal.ts
var import_obsidian6 = require("obsidian");
var AddItemsModal = class extends import_obsidian6.Modal {
  constructor(app, properties, onSubmit) {
    super(app);
    this.items = [];
    this.properties = properties;
    this.onSubmit = onSubmit;
    this.addEmptyItem();
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("checklist-modal");
    contentEl.createEl("h2", { text: "Add Multiple Items" });
    this.listContainer = contentEl.createDiv({ cls: "checklist-bulk-items" });
    this.renderItems();
    new import_obsidian6.Setting(contentEl).addButton(
      (button) => button.setButtonText("+ Add Another").onClick(() => {
        this.addEmptyItem();
        this.renderItems();
      })
    );
    new import_obsidian6.Setting(contentEl).addButton(
      (button) => button.setButtonText("Add All Items").setCta().onClick(() => {
        const validItems = this.items.filter((item) => item.name.trim());
        if (validItems.length === 0) {
          new import_obsidian6.Notice("Please enter at least one item name.");
          return;
        }
        this.onSubmit(
          validItems.map((item) => ({
            ...item,
            name: item.name.trim(),
            description: item.description.trim()
          }))
        );
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
  addEmptyItem() {
    const item = { name: "", properties: {}, description: "" };
    for (const prop of this.properties) {
      if (prop.defaultValue !== void 0) {
        item.properties[prop.name] = prop.defaultValue;
      }
    }
    this.items.push(item);
  }
  renderItems() {
    this.listContainer.empty();
    for (let i = 0; i < this.items.length; i++) {
      const item = this.items[i];
      const itemDiv = this.listContainer.createDiv({ cls: "checklist-bulk-item" });
      const header = itemDiv.createDiv({ cls: "checklist-bulk-item-header" });
      header.createSpan({ text: `Item ${i + 1}` });
      if (this.items.length > 1) {
        const removeBtn = header.createEl("button", {
          text: "Remove",
          cls: "checklist-btn-remove"
        });
        removeBtn.addEventListener("click", () => {
          this.items.splice(i, 1);
          this.renderItems();
        });
      }
      new import_obsidian6.Setting(itemDiv).setName("Name").addText(
        (text) => text.setPlaceholder("Item name").setValue(item.name).onChange((value) => {
          item.name = value;
        })
      );
      for (const prop of this.properties) {
        this.renderPropertyField(itemDiv, prop, item);
      }
      new import_obsidian6.Setting(itemDiv).setName("Description").addTextArea(
        (text) => text.setPlaceholder("Optional description...").setValue(item.description).onChange((value) => {
          item.description = value;
        })
      );
    }
  }
  renderPropertyField(container, prop, item) {
    const setting = new import_obsidian6.Setting(container).setName(prop.name);
    switch (prop.type) {
      case "text":
      case "date":
        setting.addText(
          (text) => text.setPlaceholder(prop.type === "date" ? "YYYY-MM-DD" : `Enter ${prop.name}`).setValue(String(item.properties[prop.name] || "")).onChange((value) => {
            item.properties[prop.name] = value;
          })
        );
        break;
      case "number":
        setting.addText(
          (text) => text.setPlaceholder("0").setValue(String(item.properties[prop.name] || "")).onChange((value) => {
            const num = Number(value);
            item.properties[prop.name] = isNaN(num) ? value : num;
          })
        );
        break;
      case "checkbox":
        setting.addToggle(
          (toggle) => toggle.setValue(Boolean(item.properties[prop.name])).onChange((value) => {
            item.properties[prop.name] = value;
          })
        );
        break;
      case "dropdown":
        setting.addDropdown((dropdown) => {
          dropdown.addOption("", `Select ${prop.name}...`);
          for (const option of prop.options || []) {
            dropdown.addOption(option, option);
          }
          dropdown.setValue(String(item.properties[prop.name] || "")).onChange((value) => {
            item.properties[prop.name] = value;
          });
        });
        break;
    }
  }
};

// src/models/types.ts
var DEFAULT_SETTINGS = {
  checklists: [],
  activeChecklistId: null
};

// src/main.ts
var ChecklistPlugin = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.manager = new ChecklistManager(
      this.app,
      this.settings,
      () => this.saveSettings()
    );
    this.registerView(VIEW_TYPE_CHECKLIST_SIDEBAR, (leaf) => {
      return new ChecklistSidebarView(
        leaf,
        this.manager,
        (id) => this.selectChecklist(id),
        () => this.openCreateListModal(),
        (id) => this.handleDeleteChecklist(id),
        (id, format) => this.handleExport(id, format)
      );
    });
    this.registerView(VIEW_TYPE_CHECKLIST, (leaf) => {
      return new ChecklistView(
        leaf,
        this.manager,
        () => this.openAddItemModal(),
        () => this.openAddItemsModal(),
        (filePath) => this.handleDeleteItem(filePath),
        () => this.refreshSidebar(),
        (format) => {
          const active = this.manager.getActiveChecklist();
          if (active)
            this.handleExport(active.id, format);
        }
      );
    });
    this.addRibbonIcon(ICON_CHECKLIST, "Open Checklist", () => {
      this.activateSidebar();
    });
    this.addCommand({
      id: "open-checklist-sidebar",
      name: "Open checklist sidebar",
      callback: () => this.activateSidebar()
    });
    this.addCommand({
      id: "open-checklist-view",
      name: "Open checklist view",
      callback: () => this.activateMainView()
    });
    this.addCommand({
      id: "create-new-checklist",
      name: "Create new checklist",
      callback: () => this.openCreateListModal()
    });
    this.addCommand({
      id: "add-checklist-item",
      name: "Add item to active checklist",
      callback: () => this.openAddItemModal()
    });
    this.addCommand({
      id: "add-checklist-items",
      name: "Add multiple items to active checklist",
      callback: () => this.openAddItemsModal()
    });
    this.addCommand({
      id: "export-checklist-markdown",
      name: "Export active checklist as Markdown",
      callback: () => {
        const active = this.manager.getActiveChecklist();
        if (active)
          this.handleExport(active.id, "markdown");
        else
          new import_obsidian7.Notice("No active checklist.");
      }
    });
    this.addCommand({
      id: "export-checklist-json",
      name: "Export active checklist as JSON",
      callback: () => {
        const active = this.manager.getActiveChecklist();
        if (active)
          this.handleExport(active.id, "json");
        else
          new import_obsidian7.Notice("No active checklist.");
      }
    });
    this.addCommand({
      id: "export-all-checklists-markdown",
      name: "Export all checklists as Markdown",
      callback: () => this.handleExport(null, "markdown")
    });
    this.addCommand({
      id: "export-all-checklists-json",
      name: "Export all checklists as JSON",
      callback: () => this.handleExport(null, "json")
    });
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_CHECKLIST);
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_CHECKLIST_SIDEBAR);
  }
  /**
   * Opens the sidebar in the left panel.
   */
  async activateSidebar() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_CHECKLIST_SIDEBAR);
    if (leaves.length > 0) {
      this.app.workspace.revealLeaf(leaves[0]);
      return;
    }
    const leaf = this.app.workspace.getLeftLeaf(false);
    if (leaf) {
      await leaf.setViewState({
        type: VIEW_TYPE_CHECKLIST_SIDEBAR,
        active: true
      });
      this.app.workspace.revealLeaf(leaf);
    }
  }
  /**
   * Opens the main checklist view.
   */
  async activateMainView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_CHECKLIST);
    if (leaves.length > 0) {
      this.app.workspace.revealLeaf(leaves[0]);
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false);
    if (leaf) {
      await leaf.setViewState({
        type: VIEW_TYPE_CHECKLIST,
        active: true
      });
      this.app.workspace.revealLeaf(leaf);
    }
  }
  /**
   * Selects a checklist from the sidebar, sets it active, and opens the main view.
   */
  async selectChecklist(id) {
    this.manager.setActiveChecklist(id);
    await this.activateMainView();
    this.refreshMainView();
    this.refreshSidebar();
  }
  /**
   * Handles checklist deletion with confirmation.
   */
  async handleDeleteChecklist(id) {
    const checklist = this.manager.getSettings().checklists.find((c) => c.id === id);
    if (!checklist)
      return;
    await this.manager.deleteChecklist(id);
    new import_obsidian7.Notice(`Checklist "${checklist.name}" deleted.`);
    this.refreshSidebar();
    this.refreshMainView();
  }
  /**
   * Handles item deletion.
   */
  async handleDeleteItem(filePath) {
    var _a;
    await this.manager.deleteItem(filePath);
    const name = ((_a = filePath.split("/").pop()) == null ? void 0 : _a.replace(/\.md$/, "")) || "Item";
    new import_obsidian7.Notice(`"${name}" deleted.`);
    this.refreshMainView();
    this.refreshSidebar();
  }
  /**
   * Exports a checklist (or all checklists) and saves to vault.
   */
  async handleExport(id, format) {
    const ext = format === "markdown" ? "md" : "json";
    if (id === null) {
      const content = format === "markdown" ? await this.manager.exportAllAsMarkdown() : await this.manager.exportAllAsJson();
      if (!content || content === "") {
        new import_obsidian7.Notice("No checklists to export.");
        return;
      }
      const filePath = `checklists-export.${ext}`;
      await this.saveExportFile(filePath, content);
      new import_obsidian7.Notice(`All checklists exported to ${filePath}`);
    } else {
      const checklist = this.manager.getSettings().checklists.find((c) => c.id === id);
      if (!checklist)
        return;
      const content = format === "markdown" ? await this.manager.exportChecklistAsMarkdown(id) : await this.manager.exportChecklistAsJson(id);
      const safeName = checklist.name.replace(/[\\/:*?"<>|]/g, "-");
      const filePath = `${safeName}-export.${ext}`;
      await this.saveExportFile(filePath, content);
      new import_obsidian7.Notice(`"${checklist.name}" exported to ${filePath}`);
    }
  }
  async saveExportFile(filePath, content) {
    const existing = this.app.vault.getAbstractFileByPath(filePath);
    if (existing) {
      await this.app.vault.modify(existing, content);
    } else {
      await this.app.vault.create(filePath, content);
    }
  }
  openCreateListModal() {
    new CreateListModal(this.app, async (name, properties) => {
      await this.manager.createChecklist(name, properties);
      new import_obsidian7.Notice(`Checklist "${name}" created.`);
      this.refreshSidebar();
      await this.activateMainView();
      this.refreshMainView();
    }).open();
  }
  openAddItemModal() {
    const active = this.manager.getActiveChecklist();
    if (!active) {
      new import_obsidian7.Notice("No active checklist. Create one first.");
      return;
    }
    new AddItemModal(
      this.app,
      active.properties,
      async (name, properties, description) => {
        await this.manager.addItem(active.id, name, properties, description);
        new import_obsidian7.Notice(`Item "${name}" added.`);
        this.refreshMainView();
        this.refreshSidebar();
      }
    ).open();
  }
  openAddItemsModal() {
    const active = this.manager.getActiveChecklist();
    if (!active) {
      new import_obsidian7.Notice("No active checklist. Create one first.");
      return;
    }
    new AddItemsModal(
      this.app,
      active.properties,
      async (items) => {
        const files = await this.manager.addItems(active.id, items);
        new import_obsidian7.Notice(`${files.length} item(s) added.`);
        this.refreshMainView();
        this.refreshSidebar();
      }
    ).open();
  }
  refreshMainView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_CHECKLIST);
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof ChecklistView) {
        view.renderView();
      }
    }
  }
  refreshSidebar() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_CHECKLIST_SIDEBAR);
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof ChecklistSidebarView) {
        view.renderView();
      }
    }
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
