/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ChecklistPlugin,
  migrateSettings: () => migrateSettings
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/constants.ts
var VIEW_TYPE_CHECKLIST = "checklist-sidebar";

// src/core/checklist-manager.ts
var import_obsidian = require("obsidian");

// src/core/frontmatter.ts
var FENCE = "---";
function splitFrontmatter(src) {
  let s = src;
  if (s.charCodeAt(0) === 65279)
    s = s.slice(1);
  if (!s.startsWith(FENCE))
    return null;
  const afterOpen = s.slice(FENCE.length);
  if (afterOpen[0] !== "\n" && afterOpen[0] !== "\r")
    return null;
  const rest = afterOpen.replace(/^\r?\n/, "");
  const closeRe = /\r?\n---\s*(?:\r?\n|$)/;
  const match = closeRe.exec(rest);
  if (!match || match.index === void 0)
    return null;
  return {
    block: rest.slice(0, match.index),
    body: rest.slice(match.index + match[0].length)
  };
}
var SCALAR_MAX_LEN = 4096;
function parseScalar(raw) {
  let v = raw.trim();
  if (v.length > SCALAR_MAX_LEN)
    v = v.slice(0, SCALAR_MAX_LEN);
  v = stripInlineComment(v).trim();
  if (v === "" || v === "null" || v === "~")
    return null;
  if (v === "true")
    return true;
  if (v === "false")
    return false;
  if (v.length >= 2 && v[0] === '"' && v[v.length - 1] === '"') {
    return unescapeDoubleQuoted(v.slice(1, -1));
  }
  if (v.length >= 2 && v[0] === "'" && v[v.length - 1] === "'") {
    return v.slice(1, -1).replace(/''/g, "'");
  }
  if (/^-?\d+$/.test(v)) {
    const n = Number(v);
    if (Number.isSafeInteger(n))
      return n;
  }
  if (/^-?\d+\.\d+$/.test(v)) {
    const n = Number(v);
    if (Number.isFinite(n))
      return n;
  }
  return v;
}
function unescapeDoubleQuoted(s) {
  return s.replace(/\\(.)/g, (_m, c) => {
    switch (c) {
      case "n":
        return "\n";
      case "t":
        return "	";
      case "\\":
        return "\\";
      case '"':
        return '"';
      default:
        return c;
    }
  });
}
function stripInlineComment(v) {
  let inS = null;
  for (let i = 0; i < v.length; i++) {
    const ch = v[i];
    if (inS) {
      if (ch === "\\" && i + 1 < v.length) {
        i++;
        continue;
      }
      if (ch === inS)
        inS = null;
      continue;
    }
    if (ch === '"' || ch === "'") {
      inS = ch;
      continue;
    }
    if (ch === "#" && (i === 0 || /\s/.test(v[i - 1]))) {
      return v.slice(0, i);
    }
  }
  return v;
}
function parseFlowList(raw) {
  const v = raw.trim();
  if (v.length < 2 || v[0] !== "[" || v[v.length - 1] !== "]")
    return null;
  const inner = v.slice(1, -1);
  const parts = [];
  let depth = 0;
  let inS = null;
  let start = 0;
  for (let i = 0; i < inner.length; i++) {
    const ch = inner[i];
    if (inS) {
      if (ch === "\\" && i + 1 < inner.length) {
        i++;
        continue;
      }
      if (ch === inS)
        inS = null;
      continue;
    }
    if (ch === '"' || ch === "'") {
      inS = ch;
      continue;
    }
    if (ch === "[" || ch === "{")
      depth++;
    else if (ch === "]" || ch === "}")
      depth--;
    else if (ch === "," && depth === 0) {
      parts.push(inner.slice(start, i));
      start = i + 1;
    }
  }
  parts.push(inner.slice(start));
  return parts.map((p) => p.trim()).filter((p) => p.length > 0).map((p) => parseScalar(p));
}
var MAX_LINES = 2e3;
var DANGEROUS_KEYS = /* @__PURE__ */ new Set(["__proto__", "prototype", "constructor"]);
function parseFrontmatter(src) {
  const split = splitFrontmatter(src);
  if (!split)
    return { data: {}, body: src };
  const data = /* @__PURE__ */ Object.create(null);
  const lines = split.block.split(/\r?\n/);
  let i = 0;
  let ok = true;
  const len = Math.min(lines.length, MAX_LINES);
  while (i < len) {
    const line = lines[i];
    if (line.trim() === "" || /^\s*#/.test(line)) {
      i++;
      continue;
    }
    const m = /^([A-Za-z_][A-Za-z0-9_\-]*)\s*:(.*)$/.exec(line);
    if (!m) {
      ok = false;
      break;
    }
    const key = m[1];
    const rest = m[2];
    if (DANGEROUS_KEYS.has(key)) {
      i++;
      continue;
    }
    const restTrim = rest.trim();
    if (restTrim === "") {
      let j = i + 1;
      while (j < len && /^\s*$/.test(lines[j]))
        j++;
      if (j < len && /^(\s*)-\s+/.test(lines[j])) {
        const list = [];
        while (j < len) {
          const next = lines[j];
          if (/^\s*$/.test(next)) {
            j++;
            continue;
          }
          const lm = /^(\s*)-\s+(.*)$/.exec(next);
          if (!lm)
            break;
          list.push(parseScalar(lm[2]));
          j++;
        }
        data[key] = list;
        i = j;
        continue;
      }
      data[key] = null;
      i++;
      continue;
    }
    if (restTrim[0] === "[") {
      const parsed = parseFlowList(restTrim);
      if (parsed === null) {
        ok = false;
        break;
      }
      data[key] = parsed;
      i++;
      continue;
    }
    data[key] = parseScalar(rest);
    i++;
  }
  if (!ok)
    return { data: {}, body: split.body };
  return { data, body: split.body };
}
var UNSAFE_SCALAR = /[:#\n\r"'\[\]{}&*!|>%@`]/;
var UNSAFE_IN_FLOW = /[\s,:#\n\r"'\[\]{}&*!|>%@`]/;
function quote(s) {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
function serializeFlowItem(v) {
  if (v === null || v === void 0)
    return '""';
  if (typeof v === "boolean")
    return v ? "true" : "false";
  if (typeof v === "number")
    return Number.isFinite(v) ? String(v) : '""';
  const s = String(v);
  if (s === "" || UNSAFE_IN_FLOW.test(s))
    return quote(s);
  return s;
}
function serializeValue(v) {
  if (v === null || v === void 0)
    return "";
  if (typeof v === "boolean")
    return v ? "true" : "false";
  if (typeof v === "number")
    return Number.isFinite(v) ? String(v) : "";
  if (Array.isArray(v)) {
    return `[${v.map(serializeFlowItem).join(", ")}]`;
  }
  const s = String(v);
  if (UNSAFE_SCALAR.test(s) || s.trim() !== s || s === "")
    return quote(s);
  return s;
}
var KEY_RE = /^[A-Za-z_][A-Za-z0-9_\-]*$/;
function serializeFrontmatter(data) {
  const lines = ["---"];
  for (const key of Object.keys(data)) {
    if (DANGEROUS_KEYS.has(key))
      continue;
    if (!KEY_RE.test(key))
      continue;
    const v = data[key];
    if (v === void 0)
      continue;
    lines.push(`${key}: ${serializeValue(v)}`);
  }
  lines.push("---", "");
  return lines.join("\n");
}
function updateFrontmatter(src, patch) {
  const { data, body } = parseFrontmatter(src);
  const merged = /* @__PURE__ */ Object.create(null);
  for (const k of Object.keys(data))
    merged[k] = data[k];
  for (const k of Object.keys(patch)) {
    if (DANGEROUS_KEYS.has(k))
      continue;
    if (!KEY_RE.test(k))
      continue;
    const v = patch[k];
    if (v === void 0)
      delete merged[k];
    else
      merged[k] = v;
  }
  return serializeFrontmatter(merged) + body;
}

// src/core/checklist-manager.ts
var SAFE_NAME = /^[^\\/\x00-\x1f<>:"|?*]{1,200}$/;
var RESERVED_NAMES = /* @__PURE__ */ new Set([".", "..", ""]);
function posixJoin(folder, name) {
  const f = folder.replace(/\/+$/, "");
  if (f === "")
    return `${name}.md`;
  return `${f}/${name}.md`;
}
function assertSafeName(name) {
  if (!SAFE_NAME.test(name) || RESERVED_NAMES.has(name)) {
    throw new Error(`Invalid item name: ${JSON.stringify(name)}`);
  }
  if (name.includes("..")) {
    throw new Error(`Invalid item name: ${JSON.stringify(name)}`);
  }
}
function validateProperties(def, values) {
  for (const p of def.properties) {
    const v = values[p.key];
    const missing = v === void 0 || v === null || v === "";
    if (p.required && missing) {
      throw new Error(`Property "${p.key}" is required`);
    }
    if (missing)
      continue;
    validateOne(p, v);
  }
}
function validateOne(p, v) {
  var _a, _b, _c;
  if (p.type === "number" || p.type === "rating") {
    if (typeof v !== "number" || !Number.isFinite(v)) {
      throw new Error(`Property "${p.key}" must be a number`);
    }
    if (((_a = p.validation) == null ? void 0 : _a.min) !== void 0 && v < p.validation.min) {
      throw new Error(`Property "${p.key}" must be \u2265 ${p.validation.min}`);
    }
    if (((_b = p.validation) == null ? void 0 : _b.max) !== void 0 && v > p.validation.max) {
      throw new Error(`Property "${p.key}" must be \u2264 ${p.validation.max}`);
    }
  } else if (p.type === "text" || p.type === "url") {
    if (typeof v !== "string")
      throw new Error(`Property "${p.key}" must be text`);
    if (v.length > 1e4)
      throw new Error(`Property "${p.key}" is too long`);
    if ((_c = p.validation) == null ? void 0 : _c.regex) {
      let re;
      try {
        re = new RegExp(p.validation.regex);
      } catch (e) {
        throw new Error(`Property "${p.key}" has an invalid regex`);
      }
      if (!re.test(v))
        throw new Error(`Property "${p.key}" failed validation`);
    }
  } else if (p.type === "select") {
    if (typeof v !== "string")
      throw new Error(`Property "${p.key}" must be a string`);
    if (p.options && !p.options.includes(v)) {
      throw new Error(`Property "${p.key}" must be one of ${p.options.join(", ")}`);
    }
  } else if (p.type === "multi-select") {
    if (!Array.isArray(v))
      throw new Error(`Property "${p.key}" must be a list`);
    if (p.options) {
      for (const item of v) {
        if (!p.options.includes(String(item))) {
          throw new Error(`Property "${p.key}" has invalid value ${String(item)}`);
        }
      }
    }
  }
}
var ChecklistManager = class {
  constructor(app) {
    this.app = app;
    this.cache = /* @__PURE__ */ new Map();
  }
  /** Return a shallow copy of the cached items for a checklist. */
  getCachedItems(def) {
    var _a;
    return ((_a = this.cache.get(def.id)) != null ? _a : []).slice();
  }
  /** Does this file belong to the given checklist? */
  ownsFile(def, file) {
    const folder = def.folder.replace(/\/+$/, "");
    if (folder === "")
      return !file.path.includes("/");
    const prefix = folder + "/";
    if (!file.path.startsWith(prefix))
      return false;
    const rel = file.path.slice(prefix.length);
    return rel.endsWith(".md") && !rel.includes("/");
  }
  /** Load items from disk and refresh the in-memory cache. */
  async loadItems(def) {
    const files = this.app.vault.getMarkdownFiles().filter((f) => this.ownsFile(def, f));
    const items = [];
    for (const file of files) {
      items.push(await this.readItem(def, file));
    }
    this.cache.set(def.id, items);
    return items.slice();
  }
  async readItem(def, file) {
    let data = {};
    try {
      const content = await this.app.vault.cachedRead(file);
      data = parseFrontmatter(content).data;
    } catch (e) {
      data = {};
    }
    const properties = {};
    for (const p of def.properties) {
      if (p.key in data)
        properties[p.key] = data[p.key];
    }
    const completedRaw = data.completed;
    const completed = def.kind === "list" ? false : completedRaw === true;
    const description = typeof data.description === "string" ? data.description : void 0;
    return {
      path: file.path,
      name: file.basename,
      completed,
      description,
      properties,
      createdAt: file.stat.ctime,
      mtime: file.stat.mtime
    };
  }
  /** Create a new item file and return the TFile handle. */
  async createItem(def, name, values) {
    assertSafeName(name);
    validateProperties(def, values);
    const path = posixJoin(def.folder, name);
    const existing = this.app.vault.getAbstractFileByPath(path);
    if (existing)
      throw new Error(`An item named "${name}" already exists`);
    const data = {};
    if (def.kind === "checklist")
      data.completed = false;
    for (const p of def.properties) {
      if (values[p.key] !== void 0)
        data[p.key] = values[p.key];
    }
    const body = serializeFrontmatter(data);
    try {
      await this.app.vault.createFolder(def.folder);
    } catch (e) {
    }
    const file = await this.app.vault.create(path, body);
    const item = await this.readItem(def, file);
    const arr = this.cache.get(def.id);
    if (arr)
      arr.push(item);
    return file;
  }
  /** Toggle completion on a checklist item (no-op for `list` kind). */
  async toggleItem(def, path) {
    if (def.kind === "list")
      return;
    const file = this.requireFile(path);
    const content = await this.app.vault.read(file);
    const parsed = parseFrontmatter(content);
    const current = parsed.data.completed === true;
    const updated = updateFrontmatter(content, { completed: !current });
    await this.app.vault.modify(file, updated);
    this.updateCache(def, file, { completed: !current });
  }
  /** Patch a single property value. */
  async updateItemProperty(def, path, key, value) {
    const pdef = def.properties.find((p) => p.key === key);
    if (!pdef)
      throw new Error(`Unknown property: ${key}`);
    if (value !== void 0 && value !== null && value !== "") {
      validateOne(pdef, value);
    }
    const file = this.requireFile(path);
    const content = await this.app.vault.read(file);
    const updated = updateFrontmatter(content, { [key]: value });
    await this.app.vault.modify(file, updated);
    this.updateCache(def, file, { properties: { [key]: value } });
  }
  /** Delete an item file. */
  async deleteItem(def, path) {
    const file = this.requireFile(path);
    await this.app.vault.delete(file);
    const arr = this.cache.get(def.id);
    if (arr) {
      const idx = arr.findIndex((i) => i.path === path);
      if (idx >= 0)
        arr.splice(idx, 1);
    }
  }
  /**
   * Incremental index maintenance. Call from vault event handlers.
   *
   * Returns `true` if the cache was changed — useful to decide whether
   * to re-render a view.
   */
  onFileEvent(event, file, def) {
    if (!this.ownsFile(def, file))
      return false;
    const arr = this.cache.get(def.id);
    if (!arr)
      return false;
    const idx = arr.findIndex((i) => i.path === file.path);
    if (event === "delete") {
      if (idx < 0)
        return false;
      arr.splice(idx, 1);
      return true;
    }
    const placeholder = {
      path: file.path,
      name: file.basename,
      completed: false,
      properties: {},
      createdAt: file.stat.ctime,
      mtime: file.stat.mtime
    };
    if (event === "create") {
      if (idx >= 0)
        return false;
      arr.push(placeholder);
      void this.readItem(def, file).then((real) => {
        const i = arr.findIndex((x) => x.path === file.path);
        if (i >= 0)
          arr[i] = real;
      });
      return true;
    }
    if (idx < 0) {
      arr.push(placeholder);
    }
    void this.readItem(def, file).then((real) => {
      const i = arr.findIndex((x) => x.path === file.path);
      if (i >= 0)
        arr[i] = real;
    });
    return true;
  }
  requireFile(path) {
    const af = this.app.vault.getAbstractFileByPath(path);
    if (!af || !(af instanceof import_obsidian.TFile))
      throw new Error(`File not found: ${path}`);
    return af;
  }
  updateCache(def, file, patch) {
    var _a;
    const arr = this.cache.get(def.id);
    if (!arr)
      return;
    const idx = arr.findIndex((i) => i.path === file.path);
    if (idx < 0)
      return;
    const prev = arr[idx];
    arr[idx] = {
      ...prev,
      completed: (_a = patch.completed) != null ? _a : prev.completed,
      properties: patch.properties ? { ...prev.properties, ...patch.properties } : prev.properties,
      mtime: file.stat.mtime
    };
  }
};

// src/ui/sidebar-view.ts
var import_obsidian2 = require("obsidian");

// src/core/filter.ts
function toHaystack(v) {
  if (v === null || v === void 0)
    return "";
  if (Array.isArray(v))
    return v.map(toHaystack).join(" ");
  return String(v).toLocaleLowerCase();
}
function matchesQuery(item, q) {
  if (q === "")
    return true;
  const needle = q.toLocaleLowerCase();
  if (toHaystack(item.name).includes(needle))
    return true;
  if (toHaystack(item.description).includes(needle))
    return true;
  for (const k of Object.keys(item.properties)) {
    if (toHaystack(item.properties[k]).includes(needle))
      return true;
  }
  return false;
}
function matchesStatus(item, status) {
  if (status === "all")
    return true;
  if (status === "active")
    return !item.completed;
  return item.completed;
}
function propertyAllows(item, key, allowed) {
  if (allowed.length === 0)
    return true;
  const v = item.properties[key];
  if (v === null || v === void 0)
    return false;
  if (Array.isArray(v)) {
    return v.some((iv) => allowed.some((a) => a === iv));
  }
  return allowed.some((a) => a === v);
}
function filterItems(items, opts) {
  const { query, status, properties } = opts;
  const propKeys = properties ? Object.keys(properties) : [];
  return items.filter((item) => {
    if (!matchesQuery(item, query))
      return false;
    if (!matchesStatus(item, status))
      return false;
    for (const k of propKeys) {
      if (!propertyAllows(item, k, properties[k]))
        return false;
    }
    return true;
  });
}

// src/core/sort.ts
function valueFor(item, key) {
  switch (key) {
    case "name":
      return item.name;
    case "completed":
      return item.completed;
    case "createdAt":
      return item.createdAt;
    case "mtime":
      return item.mtime;
    default:
      return item.properties[key];
  }
}
function isMissing(v) {
  if (v === null || v === void 0)
    return true;
  if (typeof v === "string" && v === "")
    return true;
  if (typeof v === "number" && !Number.isFinite(v))
    return true;
  return false;
}
function coerce(v) {
  if (typeof v === "number" || typeof v === "boolean")
    return v;
  if (v instanceof Date)
    return v.getTime();
  return String(v).toLocaleLowerCase();
}
function compare(a, b) {
  const ca = coerce(a);
  const cb = coerce(b);
  if (typeof ca === "number" && typeof cb === "number") {
    return ca === cb ? 0 : ca < cb ? -1 : 1;
  }
  if (typeof ca === "boolean" && typeof cb === "boolean") {
    return ca === cb ? 0 : ca ? 1 : -1;
  }
  const sa = String(ca);
  const sb = String(cb);
  if (sa === sb)
    return 0;
  return sa < sb ? -1 : 1;
}
function sortItems(items, opts) {
  const indexed = items.map((item, index) => ({ item, index }));
  const factor = opts.dir === "desc" ? -1 : 1;
  indexed.sort((x, y) => {
    const va = valueFor(x.item, opts.key);
    const vb = valueFor(y.item, opts.key);
    const ma = isMissing(va);
    const mb = isMissing(vb);
    if (ma && mb)
      return x.index - y.index;
    if (ma)
      return 1;
    if (mb)
      return -1;
    const c = compare(va, vb);
    if (c !== 0)
      return c * factor;
    return x.index - y.index;
  });
  return indexed.map((e) => e.item);
}

// src/core/group.ts
var EMPTY_LABEL = "\u2014";
function labelFor(item, key) {
  if (key === "completed")
    return item.completed ? "Completed" : "Active";
  const v = item.properties[key];
  if (v === null || v === void 0 || v === "")
    return EMPTY_LABEL;
  if (Array.isArray(v))
    return v.length === 0 ? EMPTY_LABEL : v.map(String).join(", ");
  return String(v);
}
function groupItems(items, key) {
  if (key === null) {
    return [{ label: "", items: items.slice(), count: items.length }];
  }
  const buckets = /* @__PURE__ */ new Map();
  for (const item of items) {
    const label = labelFor(item, key);
    const existing = buckets.get(label);
    if (existing)
      existing.push(item);
    else
      buckets.set(label, [item]);
  }
  const labels = Array.from(buckets.keys()).sort((a, b) => {
    if (a === EMPTY_LABEL)
      return 1;
    if (b === EMPTY_LABEL)
      return -1;
    return a.localeCompare(b);
  });
  return labels.map((label) => {
    const arr = buckets.get(label);
    return { label, items: arr, count: arr.length };
  });
}

// src/ui/sidebar-view.ts
function defaultViewState() {
  return {
    sort: { key: "name", dir: "asc" },
    filter: { query: "", status: "all" },
    groupBy: null
  };
}
var ChecklistSidebarView = class extends import_obsidian2.ItemView {
  constructor(leaf, deps) {
    super(leaf);
    this.activeId = null;
    this.stateById = /* @__PURE__ */ new Map();
    this.deps = deps;
  }
  getViewType() {
    return VIEW_TYPE_CHECKLIST;
  }
  getDisplayText() {
    return "Checklist";
  }
  getIcon() {
    return "check-square";
  }
  async onOpen() {
    const root = this.contentEl;
    root.empty();
    root.addClass("checklist-plugin-root");
    this.headerEl = root.createDiv({ cls: "checklist-header" });
    this.toolbarEl = root.createDiv({ cls: "checklist-toolbar" });
    this.listEl = root.createDiv({ cls: "checklist-list" });
    this.renderHeader();
    this.renderToolbar();
    const defs = this.deps.getDefinitions();
    if (defs.length > 0) {
      await this.selectChecklist(defs[0].id);
    } else {
      this.renderEmpty();
    }
  }
  async onClose() {
    this.contentEl.empty();
  }
  /** Switch to a different checklist. */
  async selectChecklist(id) {
    this.activeId = id;
    if (!this.stateById.has(id))
      this.stateById.set(id, defaultViewState());
    const def = this.definition();
    if (!def) {
      this.renderEmpty();
      return;
    }
    await this.deps.manager.loadItems(def);
    this.renderHeader();
    this.renderList();
  }
  /** Re-render only the list portion (called on filter/sort changes). */
  refresh() {
    if (!this.activeId)
      return;
    this.renderList();
  }
  // ----- rendering -----
  renderHeader() {
    this.headerEl.empty();
    const defs = this.deps.getDefinitions();
    const left = this.headerEl.createDiv({ cls: "checklist-header-left" });
    const newBtn = left.createEl("button", { text: "+ New list", cls: "checklist-new-list" });
    newBtn.addEventListener("click", () => {
      void this.deps.openCreateListModal();
    });
    const select = this.headerEl.createEl("select", { cls: "checklist-picker" });
    if (defs.length === 0) {
      select.createEl("option", { text: "No checklists", attr: { value: "" } });
      select.disabled = true;
    } else {
      for (const d of defs) {
        const opt = select.createEl("option", { text: d.name, attr: { value: d.id } });
        if (d.id === this.activeId)
          opt.selected = true;
      }
      select.addEventListener("change", () => {
        void this.selectChecklist(select.value);
      });
    }
  }
  renderToolbar() {
    this.toolbarEl.empty();
    this.searchInput = this.toolbarEl.createEl("input", {
      cls: "checklist-search",
      attr: { type: "search", placeholder: "Search\u2026" }
    });
    this.searchInput.addEventListener("input", () => {
      const st = this.currentState();
      if (!st)
        return;
      st.filter = { ...st.filter, query: this.searchInput.value };
      this.refresh();
    });
    this.statusSelect = this.toolbarEl.createEl("select", { cls: "checklist-status" });
    for (const [v, label] of [
      ["all", "All"],
      ["active", "Active"],
      ["done", "Done"]
    ]) {
      this.statusSelect.createEl("option", { text: label, attr: { value: v } });
    }
    this.statusSelect.addEventListener("change", () => {
      const st = this.currentState();
      if (!st)
        return;
      st.filter = { ...st.filter, status: this.statusSelect.value };
      this.refresh();
    });
    const addBtn = this.toolbarEl.createEl("button", { text: "+ Add", cls: "checklist-add" });
    addBtn.addEventListener("click", () => {
      const def = this.definition();
      if (def)
        void this.deps.openAddItemModal(def);
    });
  }
  renderEmpty() {
    this.listEl.empty();
    this.listEl.createDiv({
      cls: "checklist-empty",
      text: "No checklists yet. Click '+ New list' to create one."
    });
  }
  renderList() {
    const def = this.definition();
    const state = this.currentState();
    if (!def || !state) {
      this.renderEmpty();
      return;
    }
    this.listEl.empty();
    const raw = this.deps.manager.getCachedItems(def);
    const filtered = filterItems(raw, state.filter);
    const sorted = sortItems(filtered, state.sort);
    const groups = groupItems(sorted, state.groupBy);
    if (sorted.length === 0) {
      this.listEl.createDiv({ cls: "checklist-empty", text: "No items match your filters." });
      return;
    }
    for (const group of groups) {
      if (state.groupBy !== null) {
        const header = this.listEl.createDiv({ cls: "checklist-group-header" });
        header.createEl("span", { text: group.label, cls: "checklist-group-label" });
        header.createEl("span", { text: `(${group.count})`, cls: "checklist-group-count" });
      }
      for (const item of group.items) {
        this.renderItemRow(def, item);
      }
    }
  }
  renderItemRow(def, item) {
    const row = this.listEl.createDiv({ cls: "checklist-item" });
    if (item.completed)
      row.addClass("is-completed");
    if (def.kind === "checklist") {
      const box = row.createEl("input", {
        cls: "checklist-checkbox",
        attr: { type: "checkbox" }
      });
      box.checked = item.completed;
      box.addEventListener("change", async () => {
        try {
          await this.deps.manager.toggleItem(def, item.path);
          this.refresh();
        } catch (err) {
          console.error("Checklist: toggleItem failed", err);
        }
      });
    } else {
      row.createEl("span", { cls: "checklist-bullet", text: "\u2022" });
    }
    const nameEl = row.createEl("span", { cls: "checklist-item-name" });
    nameEl.textContent = item.name;
    for (const p of def.properties) {
      const v = item.properties[p.key];
      if (v === void 0 || v === null || v === "")
        continue;
      const chip = row.createEl("span", { cls: "checklist-item-prop" });
      chip.textContent = Array.isArray(v) ? v.map(String).join(", ") : String(v);
    }
  }
  currentState() {
    if (!this.activeId)
      return null;
    return this.stateById.get(this.activeId) || null;
  }
  definition() {
    if (!this.activeId)
      return null;
    return this.deps.getDefinitions().find((d) => d.id === this.activeId) || null;
  }
};

// src/main.ts
var CURRENT_SETTINGS_VERSION = 1;
var DEFAULT_SETTINGS = {
  settingsVersion: CURRENT_SETTINGS_VERSION,
  definitions: []
};
function migrateSettings(raw) {
  if (raw === null || typeof raw !== "object")
    return { ...DEFAULT_SETTINGS };
  const obj = raw;
  const version = typeof obj.settingsVersion === "number" ? obj.settingsVersion : 0;
  let settings = {
    settingsVersion: CURRENT_SETTINGS_VERSION,
    definitions: Array.isArray(obj.definitions) ? obj.definitions : []
  };
  if (version < 1) {
    settings = { ...settings, settingsVersion: 1 };
  }
  return settings;
}
var ChecklistPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
  }
  async onload() {
    await this.loadSettings();
    this.manager = new ChecklistManager(this.app);
    this.registerView(
      VIEW_TYPE_CHECKLIST,
      (leaf) => new ChecklistSidebarView(leaf, {
        manager: this.manager,
        getDefinitions: () => this.settings.definitions,
        saveSettings: () => this.saveData(this.settings),
        openAddItemModal: async (def) => this.quickAddItem(def),
        openCreateListModal: async () => this.quickCreateList()
      })
    );
    this.addRibbonIcon("check-square", "Open checklist", async () => {
      await this.activateView();
    });
    this.addCommand({
      id: "checklist-open",
      name: "Open checklist sidebar",
      callback: async () => this.activateView()
    });
    this.registerEvent(
      this.app.vault.on("create", (file) => this.handleVaultEvent("create", file))
    );
    this.registerEvent(
      this.app.vault.on("modify", (file) => this.handleVaultEvent("modify", file))
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => this.handleVaultEvent("delete", file))
    );
  }
  async onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_CHECKLIST);
  }
  async loadSettings() {
    const raw = await this.loadData();
    this.settings = migrateSettings(raw);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /** Open the view in the LEFT sidebar only. */
  async activateView() {
    const { workspace } = this.app;
    const existing = workspace.getLeavesOfType(VIEW_TYPE_CHECKLIST);
    let leaf;
    if (existing.length > 0) {
      leaf = existing[0];
    } else {
      leaf = workspace.getLeftLeaf(false);
      if (!leaf) {
        new import_obsidian3.Notice("Could not open left sidebar leaf");
        return;
      }
      await leaf.setViewState({ type: VIEW_TYPE_CHECKLIST, active: true });
    }
    if (leaf)
      workspace.revealLeaf(leaf);
  }
  handleVaultEvent(event, file) {
    if (!(file instanceof import_obsidian3.TFile))
      return;
    if (file.extension !== "md")
      return;
    let changed = false;
    for (const def of this.settings.definitions) {
      if (this.manager.onFileEvent(event, file, def))
        changed = true;
    }
    if (changed) {
      const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_CHECKLIST);
      for (const leaf of leaves) {
        const v = leaf.view;
        if (v instanceof ChecklistSidebarView)
          v.refresh();
      }
    }
  }
  /**
   * Temporary lightweight "quick add" — asks via Notice until a modal is
   * needed. TASKS 3.5 (Quick-add bar) can later route through the toolbar
   * input directly.
   */
  async quickAddItem(def) {
    const name = typeof window !== "undefined" ? window.prompt(`New item in "${def.name}"`) : null;
    if (!name)
      return;
    try {
      await this.manager.createItem(def, name, {});
      new import_obsidian3.Notice(`Added "${name}"`);
    } catch (err) {
      new import_obsidian3.Notice(`Failed to add item: ${err.message}`);
    }
  }
  async quickCreateList() {
    const name = typeof window !== "undefined" ? window.prompt("Name the new checklist:") : null;
    if (!name)
      return;
    const id = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
    if (!id) {
      new import_obsidian3.Notice("Invalid checklist name");
      return;
    }
    if (this.settings.definitions.find((d) => d.id === id)) {
      new import_obsidian3.Notice("A checklist with that id already exists");
      return;
    }
    const def = {
      id,
      name,
      kind: "checklist",
      folder: name,
      properties: []
    };
    this.settings.definitions.push(def);
    await this.saveSettings();
    await this.activateView();
  }
};
